// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/mikestefanello/pagoda/ent/customer"
	"github.com/mikestefanello/pagoda/ent/glog"
	"github.com/mikestefanello/pagoda/ent/gorder"
	"github.com/mikestefanello/pagoda/ent/guide"
	"github.com/mikestefanello/pagoda/ent/ordernumber"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/schema"
	"github.com/mikestefanello/pagoda/ent/shedule"
	"github.com/mikestefanello/pagoda/ent/transport"
	"github.com/mikestefanello/pagoda/ent/trip"
	"github.com/mikestefanello/pagoda/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescFirstname is the schema descriptor for firstname field.
	customerDescFirstname := customerFields[0].Descriptor()
	// customer.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	customer.FirstnameValidator = customerDescFirstname.Validators[0].(func(string) error)
	// customerDescLastname is the schema descriptor for lastname field.
	customerDescLastname := customerFields[1].Descriptor()
	// customer.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	customer.LastnameValidator = customerDescLastname.Validators[0].(func(string) error)
	// customerDescActive is the schema descriptor for active field.
	customerDescActive := customerFields[4].Descriptor()
	// customer.DefaultActive holds the default value on creation for the active field.
	customer.DefaultActive = customerDescActive.Default.(bool)
	// customerDescCreated is the schema descriptor for created field.
	customerDescCreated := customerFields[7].Descriptor()
	// customer.DefaultCreated holds the default value on creation for the created field.
	customer.DefaultCreated = customerDescCreated.Default.(time.Time)
	// customerDescUpdated is the schema descriptor for updated field.
	customerDescUpdated := customerFields[8].Descriptor()
	// customer.DefaultUpdated holds the default value on creation for the updated field.
	customer.DefaultUpdated = customerDescUpdated.Default.(time.Time)
	// customerDescCreatedBy is the schema descriptor for created_by field.
	customerDescCreatedBy := customerFields[9].Descriptor()
	// customer.DefaultCreatedBy holds the default value on creation for the created_by field.
	customer.DefaultCreatedBy = customerDescCreatedBy.Default.(int)
	glogFields := schema.GLog{}.Fields()
	_ = glogFields
	// glogDescAction is the schema descriptor for action field.
	glogDescAction := glogFields[0].Descriptor()
	// glog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	glog.ActionValidator = glogDescAction.Validators[0].(func(string) error)
	// glogDescCreated is the schema descriptor for created field.
	glogDescCreated := glogFields[2].Descriptor()
	// glog.DefaultCreated holds the default value on creation for the created field.
	glog.DefaultCreated = glogDescCreated.Default.(time.Time)
	// glogDescCreatedBy is the schema descriptor for created_by field.
	glogDescCreatedBy := glogFields[3].Descriptor()
	// glog.DefaultCreatedBy holds the default value on creation for the created_by field.
	glog.DefaultCreatedBy = glogDescCreatedBy.Default.(int)
	gorderFields := schema.GOrder{}.Fields()
	_ = gorderFields
	// gorderDescNum is the schema descriptor for num field.
	gorderDescNum := gorderFields[0].Descriptor()
	// gorder.DefaultNum holds the default value on creation for the num field.
	gorder.DefaultNum = gorderDescNum.Default.(int)
	// gorderDescTripID is the schema descriptor for trip_id field.
	gorderDescTripID := gorderFields[1].Descriptor()
	// gorder.DefaultTripID holds the default value on creation for the trip_id field.
	gorder.DefaultTripID = gorderDescTripID.Default.(int)
	// gorderDescCountPerson is the schema descriptor for count_person field.
	gorderDescCountPerson := gorderFields[2].Descriptor()
	// gorder.DefaultCountPerson holds the default value on creation for the count_person field.
	gorder.DefaultCountPerson = gorderDescCountPerson.Default.(int)
	// gorderDescTransportID is the schema descriptor for transport_id field.
	gorderDescTransportID := gorderFields[5].Descriptor()
	// gorder.DefaultTransportID holds the default value on creation for the transport_id field.
	gorder.DefaultTransportID = gorderDescTransportID.Default.(int)
	// gorderDescGuideID is the schema descriptor for guide_id field.
	gorderDescGuideID := gorderFields[6].Descriptor()
	// gorder.DefaultGuideID holds the default value on creation for the guide_id field.
	gorder.DefaultGuideID = gorderDescGuideID.Default.(int)
	// gorderDescCost is the schema descriptor for cost field.
	gorderDescCost := gorderFields[7].Descriptor()
	// gorder.DefaultCost holds the default value on creation for the cost field.
	gorder.DefaultCost = gorderDescCost.Default.(int)
	// gorderDescStatus is the schema descriptor for status field.
	gorderDescStatus := gorderFields[8].Descriptor()
	// gorder.DefaultStatus holds the default value on creation for the status field.
	gorder.DefaultStatus = gorderDescStatus.Default.(int)
	// gorderDescPayStatus is the schema descriptor for pay_status field.
	gorderDescPayStatus := gorderFields[9].Descriptor()
	// gorder.DefaultPayStatus holds the default value on creation for the pay_status field.
	gorder.DefaultPayStatus = gorderDescPayStatus.Default.(int)
	// gorderDescPaidSum is the schema descriptor for paid_sum field.
	gorderDescPaidSum := gorderFields[10].Descriptor()
	// gorder.DefaultPaidSum holds the default value on creation for the paid_sum field.
	gorder.DefaultPaidSum = gorderDescPaidSum.Default.(int)
	// gorderDescCustomerID is the schema descriptor for customer_id field.
	gorderDescCustomerID := gorderFields[11].Descriptor()
	// gorder.DefaultCustomerID holds the default value on creation for the customer_id field.
	gorder.DefaultCustomerID = gorderDescCustomerID.Default.(int)
	// gorderDescCreated is the schema descriptor for created field.
	gorderDescCreated := gorderFields[14].Descriptor()
	// gorder.DefaultCreated holds the default value on creation for the created field.
	gorder.DefaultCreated = gorderDescCreated.Default.(time.Time)
	// gorderDescUpdated is the schema descriptor for updated field.
	gorderDescUpdated := gorderFields[15].Descriptor()
	// gorder.DefaultUpdated holds the default value on creation for the updated field.
	gorder.DefaultUpdated = gorderDescUpdated.Default.(time.Time)
	// gorderDescCreatedBy is the schema descriptor for created_by field.
	gorderDescCreatedBy := gorderFields[16].Descriptor()
	// gorder.DefaultCreatedBy holds the default value on creation for the created_by field.
	gorder.DefaultCreatedBy = gorderDescCreatedBy.Default.(int)
	// gorderDescArchived is the schema descriptor for archived field.
	gorderDescArchived := gorderFields[17].Descriptor()
	// gorder.DefaultArchived holds the default value on creation for the archived field.
	gorder.DefaultArchived = gorderDescArchived.Default.(bool)
	guideFields := schema.Guide{}.Fields()
	_ = guideFields
	// guideDescFirstname is the schema descriptor for firstname field.
	guideDescFirstname := guideFields[0].Descriptor()
	// guide.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	guide.FirstnameValidator = guideDescFirstname.Validators[0].(func(string) error)
	// guideDescLastname is the schema descriptor for lastname field.
	guideDescLastname := guideFields[1].Descriptor()
	// guide.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	guide.LastnameValidator = guideDescLastname.Validators[0].(func(string) error)
	// guideDescActive is the schema descriptor for active field.
	guideDescActive := guideFields[4].Descriptor()
	// guide.DefaultActive holds the default value on creation for the active field.
	guide.DefaultActive = guideDescActive.Default.(bool)
	ordernumberFields := schema.OrderNumber{}.Fields()
	_ = ordernumberFields
	// ordernumberDescNum is the schema descriptor for num field.
	ordernumberDescNum := ordernumberFields[0].Descriptor()
	// ordernumber.DefaultNum holds the default value on creation for the num field.
	ordernumber.DefaultNum = ordernumberDescNum.Default.(int)
	passwordtokenHooks := schema.PasswordToken{}.Hooks()
	passwordtoken.Hooks[0] = passwordtokenHooks[0]
	passwordtokenFields := schema.PasswordToken{}.Fields()
	_ = passwordtokenFields
	// passwordtokenDescToken is the schema descriptor for token field.
	passwordtokenDescToken := passwordtokenFields[0].Descriptor()
	// passwordtoken.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	passwordtoken.TokenValidator = passwordtokenDescToken.Validators[0].(func(string) error)
	// passwordtokenDescCreatedAt is the schema descriptor for created_at field.
	passwordtokenDescCreatedAt := passwordtokenFields[2].Descriptor()
	// passwordtoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	passwordtoken.DefaultCreatedAt = passwordtokenDescCreatedAt.Default.(func() time.Time)
	sheduleFields := schema.Shedule{}.Fields()
	_ = sheduleFields
	// sheduleDescComment is the schema descriptor for comment field.
	sheduleDescComment := sheduleFields[4].Descriptor()
	// shedule.DefaultComment holds the default value on creation for the comment field.
	shedule.DefaultComment = sheduleDescComment.Default.(string)
	transportFields := schema.Transport{}.Fields()
	_ = transportFields
	// transportDescName is the schema descriptor for name field.
	transportDescName := transportFields[0].Descriptor()
	// transport.NameValidator is a validator for the "name" field. It is called by the builders before save.
	transport.NameValidator = transportDescName.Validators[0].(func(string) error)
	// transportDescMinCount is the schema descriptor for min_count field.
	transportDescMinCount := transportFields[2].Descriptor()
	// transport.DefaultMinCount holds the default value on creation for the min_count field.
	transport.DefaultMinCount = transportDescMinCount.Default.(int)
	// transportDescMaxCount is the schema descriptor for max_count field.
	transportDescMaxCount := transportFields[3].Descriptor()
	// transport.DefaultMaxCount holds the default value on creation for the max_count field.
	transport.DefaultMaxCount = transportDescMaxCount.Default.(int)
	// transportDescActive is the schema descriptor for active field.
	transportDescActive := transportFields[4].Descriptor()
	// transport.DefaultActive holds the default value on creation for the active field.
	transport.DefaultActive = transportDescActive.Default.(bool)
	tripFields := schema.Trip{}.Fields()
	_ = tripFields
	// tripDescName is the schema descriptor for name field.
	tripDescName := tripFields[0].Descriptor()
	// trip.NameValidator is a validator for the "name" field. It is called by the builders before save.
	trip.NameValidator = tripDescName.Validators[0].(func(string) error)
	// tripDescActive is the schema descriptor for active field.
	tripDescActive := tripFields[4].Descriptor()
	// trip.DefaultActive holds the default value on creation for the active field.
	trip.DefaultActive = tripDescActive.Default.(bool)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescVerified is the schema descriptor for verified field.
	userDescVerified := userFields[3].Descriptor()
	// user.DefaultVerified holds the default value on creation for the verified field.
	user.DefaultVerified = userDescVerified.Default.(bool)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[4].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
