// Code generated by ent, DO NOT EDIT.

package transport

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the transport type in the database.
	Label = "transport"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMinCount holds the string denoting the min_count field in the database.
	FieldMinCount = "min_count"
	// FieldMaxCount holds the string denoting the max_count field in the database.
	FieldMaxCount = "max_count"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// Table holds the table name of the transport in the database.
	Table = "transports"
)

// Columns holds all SQL columns for transport fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldMinCount,
	FieldMaxCount,
	FieldActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultMinCount holds the default value on creation for the "min_count" field.
	DefaultMinCount int
	// DefaultMaxCount holds the default value on creation for the "max_count" field.
	DefaultMaxCount int
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
)

// OrderOption defines the ordering options for the Transport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByMinCount orders the results by the min_count field.
func ByMinCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinCount, opts...).ToFunc()
}

// ByMaxCount orders the results by the max_count field.
func ByMaxCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxCount, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}
