// Code generated by ent, DO NOT EDIT.
package admin

import (
	"fmt"
	"net/url"
	"strconv"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/labstack/echo/v4"

	"github.com/mikestefanello/pagoda/ent"
	"github.com/mikestefanello/pagoda/ent/cost"
	"github.com/mikestefanello/pagoda/ent/customer"
	"github.com/mikestefanello/pagoda/ent/glog"
	"github.com/mikestefanello/pagoda/ent/gorder"
	"github.com/mikestefanello/pagoda/ent/guide"
	"github.com/mikestefanello/pagoda/ent/ordernumber"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/shedule"
	"github.com/mikestefanello/pagoda/ent/transport"
	"github.com/mikestefanello/pagoda/ent/trip"
	"github.com/mikestefanello/pagoda/ent/user"
)

const dateTimeFormat = "2006-01-02T15:04:05"
const dateTimeFormatNoSeconds = "2006-01-02T15:04"

type Handler struct {
	client *ent.Client
	Config HandlerConfig
}

func NewHandler(client *ent.Client, cfg HandlerConfig) *Handler {
	return &Handler{
		client: client,
		Config: cfg,
	}
}

func (h *Handler) Create(ctx echo.Context, entityType EntityType) error {
	switch entityType.(type) {
	case *Cost:
		return h.CostCreate(ctx)
	case *Customer:
		return h.CustomerCreate(ctx)
	case *GLog:
		return h.GLogCreate(ctx)
	case *GOrder:
		return h.GOrderCreate(ctx)
	case *Guide:
		return h.GuideCreate(ctx)
	case *OrderNumber:
		return h.OrderNumberCreate(ctx)
	case *PasswordToken:
		return h.PasswordTokenCreate(ctx)
	case *Shedule:
		return h.SheduleCreate(ctx)
	case *Transport:
		return h.TransportCreate(ctx)
	case *Trip:
		return h.TripCreate(ctx)
	case *User:
		return h.UserCreate(ctx)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Get(ctx echo.Context, entityType EntityType, id int) (url.Values, error) {
	switch entityType.(type) {
	case *Cost:
		return h.CostGet(ctx, id)
	case *Customer:
		return h.CustomerGet(ctx, id)
	case *GLog:
		return h.GLogGet(ctx, id)
	case *GOrder:
		return h.GOrderGet(ctx, id)
	case *Guide:
		return h.GuideGet(ctx, id)
	case *OrderNumber:
		return h.OrderNumberGet(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenGet(ctx, id)
	case *Shedule:
		return h.SheduleGet(ctx, id)
	case *Transport:
		return h.TransportGet(ctx, id)
	case *Trip:
		return h.TripGet(ctx, id)
	case *User:
		return h.UserGet(ctx, id)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Delete(ctx echo.Context, entityType EntityType, id int) error {
	switch entityType.(type) {
	case *Cost:
		return h.CostDelete(ctx, id)
	case *Customer:
		return h.CustomerDelete(ctx, id)
	case *GLog:
		return h.GLogDelete(ctx, id)
	case *GOrder:
		return h.GOrderDelete(ctx, id)
	case *Guide:
		return h.GuideDelete(ctx, id)
	case *OrderNumber:
		return h.OrderNumberDelete(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenDelete(ctx, id)
	case *Shedule:
		return h.SheduleDelete(ctx, id)
	case *Transport:
		return h.TransportDelete(ctx, id)
	case *Trip:
		return h.TripDelete(ctx, id)
	case *User:
		return h.UserDelete(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) Update(ctx echo.Context, entityType EntityType, id int) error {
	switch entityType.(type) {
	case *Cost:
		return h.CostUpdate(ctx, id)
	case *Customer:
		return h.CustomerUpdate(ctx, id)
	case *GLog:
		return h.GLogUpdate(ctx, id)
	case *GOrder:
		return h.GOrderUpdate(ctx, id)
	case *Guide:
		return h.GuideUpdate(ctx, id)
	case *OrderNumber:
		return h.OrderNumberUpdate(ctx, id)
	case *PasswordToken:
		return h.PasswordTokenUpdate(ctx, id)
	case *Shedule:
		return h.SheduleUpdate(ctx, id)
	case *Transport:
		return h.TransportUpdate(ctx, id)
	case *Trip:
		return h.TripUpdate(ctx, id)
	case *User:
		return h.UserUpdate(ctx, id)
	default:
		return fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) List(ctx echo.Context, entityType EntityType) (*EntityList, error) {
	switch entityType.(type) {
	case *Cost:
		return h.CostList(ctx)
	case *Customer:
		return h.CustomerList(ctx)
	case *GLog:
		return h.GLogList(ctx)
	case *GOrder:
		return h.GOrderList(ctx)
	case *Guide:
		return h.GuideList(ctx)
	case *OrderNumber:
		return h.OrderNumberList(ctx)
	case *PasswordToken:
		return h.PasswordTokenList(ctx)
	case *Shedule:
		return h.SheduleList(ctx)
	case *Transport:
		return h.TransportList(ctx)
	case *Trip:
		return h.TripList(ctx)
	case *User:
		return h.UserList(ctx)
	default:
		return nil, fmt.Errorf("unsupported entity type: %s", entityType)
	}
}

func (h *Handler) CostCreate(ctx echo.Context) error {
	var payload Cost
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Cost.Create()
	if payload.Cost != nil {
		op.SetCost(*payload.Cost)
	}
	if payload.TripID != nil {
		op.SetTripID(*payload.TripID)
	}
	if payload.TransportID != nil {
		op.SetTransportID(*payload.TransportID)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CostUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Cost.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Cost
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Cost == nil {
		var empty int
		op.SetCost(empty)
	} else {
		op.SetCost(*payload.Cost)
	}
	if payload.TripID == nil {
		var empty int
		op.SetTripID(empty)
	} else {
		op.SetTripID(*payload.TripID)
	}
	if payload.TransportID == nil {
		var empty int
		op.SetTransportID(empty)
	} else {
		op.SetTransportID(*payload.TransportID)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CostDelete(ctx echo.Context, id int) error {
	return h.client.Cost.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) CostList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Cost.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(cost.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Cost",
			"Trip ID",
			"Transport ID",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].Cost),
				fmt.Sprint(res[i].TripID),
				fmt.Sprint(res[i].TransportID),
			},
		})
	}

	return list, err
}

func (h *Handler) CostGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Cost.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("cost", fmt.Sprint(entity.Cost))
	v.Set("trip_id", fmt.Sprint(entity.TripID))
	v.Set("transport_id", fmt.Sprint(entity.TransportID))
	return v, err
}

func (h *Handler) CustomerCreate(ctx echo.Context) error {
	var payload Customer
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Customer.Create()
	op.SetFirstname(payload.Firstname)
	op.SetLastname(payload.Lastname)
	op.SetPhone(payload.Phone)
	op.SetComment(payload.Comment)
	op.SetActive(payload.Active)
	op.SetEmail(payload.Email)
	op.SetPassword(payload.Password)
	if payload.Created != nil {
		op.SetCreated(*payload.Created)
	}
	if payload.Updated != nil {
		op.SetUpdated(*payload.Updated)
	}
	if payload.CreatedBy != nil {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CustomerUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Customer.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Customer
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetFirstname(payload.Firstname)
	op.SetLastname(payload.Lastname)
	op.SetPhone(payload.Phone)
	op.SetComment(payload.Comment)
	op.SetActive(payload.Active)
	op.SetEmail(payload.Email)
	op.SetPassword(payload.Password)
	if payload.Updated == nil {
		var empty time.Time
		op.SetUpdated(empty)
	} else {
		op.SetUpdated(*payload.Updated)
	}
	if payload.CreatedBy == nil {
		var empty int
		op.SetCreatedBy(empty)
	} else {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) CustomerDelete(ctx echo.Context, id int) error {
	return h.client.Customer.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) CustomerList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Customer.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(customer.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Firstname",
			"Lastname",
			"Phone",
			"Comment",
			"Active",
			"Email",
			"Password",
			"Created",
			"Updated",
			"Created by",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Firstname,
				res[i].Lastname,
				res[i].Phone,
				res[i].Comment,
				fmt.Sprint(res[i].Active),
				res[i].Email,
				res[i].Password,
				res[i].Created.Format(h.Config.TimeFormat),
				res[i].Updated.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].CreatedBy),
			},
		})
	}

	return list, err
}

func (h *Handler) CustomerGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Customer.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("firstname", entity.Firstname)
	v.Set("lastname", entity.Lastname)
	v.Set("phone", entity.Phone)
	v.Set("comment", entity.Comment)
	v.Set("active", fmt.Sprint(entity.Active))
	v.Set("email", entity.Email)
	v.Set("password", entity.Password)
	v.Set("updated", entity.Updated.Format(dateTimeFormat))
	v.Set("created_by", fmt.Sprint(entity.CreatedBy))
	return v, err
}

func (h *Handler) GLogCreate(ctx echo.Context) error {
	var payload GLog
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.GLog.Create()
	op.SetAction(payload.Action)
	op.SetComment(payload.Comment)
	if payload.Created != nil {
		op.SetCreated(*payload.Created)
	}
	if payload.CreatedBy != nil {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GLogUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.GLog.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload GLog
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetAction(payload.Action)
	op.SetComment(payload.Comment)
	if payload.CreatedBy == nil {
		var empty int
		op.SetCreatedBy(empty)
	} else {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GLogDelete(ctx echo.Context, id int) error {
	return h.client.GLog.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) GLogList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.GLog.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(glog.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Action",
			"Comment",
			"Created",
			"Created by",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Action,
				res[i].Comment,
				res[i].Created.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].CreatedBy),
			},
		})
	}

	return list, err
}

func (h *Handler) GLogGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.GLog.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("action", entity.Action)
	v.Set("comment", entity.Comment)
	v.Set("created_by", fmt.Sprint(entity.CreatedBy))
	return v, err
}

func (h *Handler) GOrderCreate(ctx echo.Context) error {
	var payload GOrder
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.GOrder.Create()
	if payload.Num != nil {
		op.SetNum(*payload.Num)
	}
	if payload.TripID != nil {
		op.SetTripID(*payload.TripID)
	}
	if payload.TouristCount != nil {
		op.SetTouristCount(*payload.TouristCount)
	}
	op.SetDay(payload.Day)
	op.SetBegin(payload.Begin)
	if payload.TransportID != nil {
		op.SetTransportID(*payload.TransportID)
	}
	if payload.GuideID != nil {
		op.SetGuideID(*payload.GuideID)
	}
	if payload.Cost != nil {
		op.SetCost(*payload.Cost)
	}
	if payload.Status != nil {
		op.SetStatus(*payload.Status)
	}
	if payload.PayStatus != nil {
		op.SetPayStatus(*payload.PayStatus)
	}
	if payload.PaidSum != nil {
		op.SetPaidSum(*payload.PaidSum)
	}
	if payload.CustomerID != nil {
		op.SetCustomerID(*payload.CustomerID)
	}
	op.SetPlace(payload.Place)
	op.SetComment(payload.Comment)
	if payload.Created != nil {
		op.SetCreated(*payload.Created)
	}
	if payload.Updated != nil {
		op.SetUpdated(*payload.Updated)
	}
	if payload.CreatedBy != nil {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	op.SetArchived(payload.Archived)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GOrderUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.GOrder.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload GOrder
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Num == nil {
		var empty int
		op.SetNum(empty)
	} else {
		op.SetNum(*payload.Num)
	}
	if payload.TripID == nil {
		var empty int
		op.SetTripID(empty)
	} else {
		op.SetTripID(*payload.TripID)
	}
	if payload.TouristCount == nil {
		var empty int
		op.SetTouristCount(empty)
	} else {
		op.SetTouristCount(*payload.TouristCount)
	}
	op.SetDay(payload.Day)
	op.SetBegin(payload.Begin)
	if payload.TransportID == nil {
		var empty int
		op.SetTransportID(empty)
	} else {
		op.SetTransportID(*payload.TransportID)
	}
	if payload.GuideID == nil {
		var empty int
		op.SetGuideID(empty)
	} else {
		op.SetGuideID(*payload.GuideID)
	}
	if payload.Cost == nil {
		var empty int
		op.SetCost(empty)
	} else {
		op.SetCost(*payload.Cost)
	}
	if payload.Status == nil {
		var empty int
		op.SetStatus(empty)
	} else {
		op.SetStatus(*payload.Status)
	}
	if payload.PayStatus == nil {
		var empty int
		op.SetPayStatus(empty)
	} else {
		op.SetPayStatus(*payload.PayStatus)
	}
	if payload.PaidSum == nil {
		var empty int
		op.SetPaidSum(empty)
	} else {
		op.SetPaidSum(*payload.PaidSum)
	}
	if payload.CustomerID == nil {
		var empty int
		op.SetCustomerID(empty)
	} else {
		op.SetCustomerID(*payload.CustomerID)
	}
	op.SetPlace(payload.Place)
	op.SetComment(payload.Comment)
	if payload.Updated == nil {
		var empty time.Time
		op.SetUpdated(empty)
	} else {
		op.SetUpdated(*payload.Updated)
	}
	if payload.CreatedBy == nil {
		var empty int
		op.SetCreatedBy(empty)
	} else {
		op.SetCreatedBy(*payload.CreatedBy)
	}
	op.SetArchived(payload.Archived)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GOrderDelete(ctx echo.Context, id int) error {
	return h.client.GOrder.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) GOrderList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.GOrder.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(gorder.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Num",
			"Trip ID",
			"Tourist count",
			"Day",
			"Begin",
			"Transport ID",
			"Guide ID",
			"Cost",
			"Status",
			"Pay status",
			"Paid sum",
			"Customer ID",
			"Place",
			"Comment",
			"Created",
			"Updated",
			"Created by",
			"Archived",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].Num),
				fmt.Sprint(res[i].TripID),
				fmt.Sprint(res[i].TouristCount),
				res[i].Day.Format(h.Config.TimeFormat),
				res[i].Begin.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].TransportID),
				fmt.Sprint(res[i].GuideID),
				fmt.Sprint(res[i].Cost),
				fmt.Sprint(res[i].Status),
				fmt.Sprint(res[i].PayStatus),
				fmt.Sprint(res[i].PaidSum),
				fmt.Sprint(res[i].CustomerID),
				res[i].Place,
				res[i].Comment,
				res[i].Created.Format(h.Config.TimeFormat),
				res[i].Updated.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].CreatedBy),
				fmt.Sprint(res[i].Archived),
			},
		})
	}

	return list, err
}

func (h *Handler) GOrderGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.GOrder.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("num", fmt.Sprint(entity.Num))
	v.Set("trip_id", fmt.Sprint(entity.TripID))
	v.Set("tourist_count", fmt.Sprint(entity.TouristCount))
	v.Set("day", entity.Day.Format(dateTimeFormat))
	v.Set("begin", entity.Begin.Format(dateTimeFormat))
	v.Set("transport_id", fmt.Sprint(entity.TransportID))
	v.Set("guide_id", fmt.Sprint(entity.GuideID))
	v.Set("cost", fmt.Sprint(entity.Cost))
	v.Set("status", fmt.Sprint(entity.Status))
	v.Set("pay_status", fmt.Sprint(entity.PayStatus))
	v.Set("paid_sum", fmt.Sprint(entity.PaidSum))
	v.Set("customer_id", fmt.Sprint(entity.CustomerID))
	v.Set("place", entity.Place)
	v.Set("comment", entity.Comment)
	v.Set("updated", entity.Updated.Format(dateTimeFormat))
	v.Set("created_by", fmt.Sprint(entity.CreatedBy))
	v.Set("archived", fmt.Sprint(entity.Archived))
	return v, err
}

func (h *Handler) GuideCreate(ctx echo.Context) error {
	var payload Guide
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Guide.Create()
	op.SetFirstname(payload.Firstname)
	op.SetLastname(payload.Lastname)
	op.SetPhone(payload.Phone)
	op.SetComment(payload.Comment)
	op.SetActive(payload.Active)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GuideUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Guide.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Guide
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetFirstname(payload.Firstname)
	op.SetLastname(payload.Lastname)
	op.SetPhone(payload.Phone)
	op.SetComment(payload.Comment)
	op.SetActive(payload.Active)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) GuideDelete(ctx echo.Context, id int) error {
	return h.client.Guide.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) GuideList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Guide.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(guide.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Firstname",
			"Lastname",
			"Phone",
			"Comment",
			"Active",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Firstname,
				res[i].Lastname,
				res[i].Phone,
				res[i].Comment,
				fmt.Sprint(res[i].Active),
			},
		})
	}

	return list, err
}

func (h *Handler) GuideGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Guide.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("firstname", entity.Firstname)
	v.Set("lastname", entity.Lastname)
	v.Set("phone", entity.Phone)
	v.Set("comment", entity.Comment)
	v.Set("active", fmt.Sprint(entity.Active))
	return v, err
}

func (h *Handler) OrderNumberCreate(ctx echo.Context) error {
	var payload OrderNumber
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.OrderNumber.Create()
	if payload.Num != nil {
		op.SetNum(*payload.Num)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) OrderNumberUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.OrderNumber.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload OrderNumber
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Num == nil {
		var empty int
		op.SetNum(empty)
	} else {
		op.SetNum(*payload.Num)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) OrderNumberDelete(ctx echo.Context, id int) error {
	return h.client.OrderNumber.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) OrderNumberList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.OrderNumber.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(ordernumber.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Num",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].Num),
			},
		})
	}

	return list, err
}

func (h *Handler) OrderNumberGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.OrderNumber.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("num", fmt.Sprint(entity.Num))
	return v, err
}

func (h *Handler) PasswordTokenCreate(ctx echo.Context) error {
	var payload PasswordToken
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.PasswordToken.Create()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload PasswordToken
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	if payload.Token != nil {
		op.SetToken(*payload.Token)
	}
	op.SetUserID(payload.UserID)
	if payload.CreatedAt == nil {
		var empty time.Time
		op.SetCreatedAt(empty)
	} else {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) PasswordTokenDelete(ctx echo.Context, id int) error {
	return h.client.PasswordToken.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) PasswordTokenList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.PasswordToken.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(passwordtoken.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"User ID",
			"Created at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].UserID),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) PasswordTokenGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.PasswordToken.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("user_id", fmt.Sprint(entity.UserID))
	v.Set("created_at", entity.CreatedAt.Format(dateTimeFormat))
	return v, err
}

func (h *Handler) SheduleCreate(ctx echo.Context) error {
	var payload Shedule
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Shedule.Create()
	op.SetResourceType(payload.ResourceType)
	op.SetResourceID(payload.ResourceID)
	op.SetBegin(payload.Begin)
	op.SetEnd(payload.End)
	if payload.Comment != nil {
		op.SetComment(*payload.Comment)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) SheduleUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Shedule.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Shedule
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetResourceType(payload.ResourceType)
	op.SetResourceID(payload.ResourceID)
	op.SetBegin(payload.Begin)
	op.SetEnd(payload.End)
	if payload.Comment == nil {
		var empty string
		op.SetComment(empty)
	} else {
		op.SetComment(*payload.Comment)
	}
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) SheduleDelete(ctx echo.Context, id int) error {
	return h.client.Shedule.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) SheduleList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Shedule.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(shedule.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Resource type",
			"Resource ID",
			"Begin",
			"End",
			"Comment",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				fmt.Sprint(res[i].ResourceType),
				fmt.Sprint(res[i].ResourceID),
				res[i].Begin.Format(h.Config.TimeFormat),
				res[i].End.Format(h.Config.TimeFormat),
				res[i].Comment,
			},
		})
	}

	return list, err
}

func (h *Handler) SheduleGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Shedule.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("resource_type", fmt.Sprint(entity.ResourceType))
	v.Set("resource_id", fmt.Sprint(entity.ResourceID))
	v.Set("begin", entity.Begin.Format(dateTimeFormat))
	v.Set("end", entity.End.Format(dateTimeFormat))
	v.Set("comment", entity.Comment)
	return v, err
}

func (h *Handler) TransportCreate(ctx echo.Context) error {
	var payload Transport
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Transport.Create()
	op.SetName(payload.Name)
	op.SetDescription(payload.Description)
	if payload.MinCount != nil {
		op.SetMinCount(*payload.MinCount)
	}
	if payload.MaxCount != nil {
		op.SetMaxCount(*payload.MaxCount)
	}
	op.SetActive(payload.Active)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) TransportUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Transport.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Transport
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetName(payload.Name)
	op.SetDescription(payload.Description)
	if payload.MinCount == nil {
		var empty int
		op.SetMinCount(empty)
	} else {
		op.SetMinCount(*payload.MinCount)
	}
	if payload.MaxCount == nil {
		var empty int
		op.SetMaxCount(empty)
	} else {
		op.SetMaxCount(*payload.MaxCount)
	}
	op.SetActive(payload.Active)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) TransportDelete(ctx echo.Context, id int) error {
	return h.client.Transport.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) TransportList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Transport.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(transport.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Name",
			"Description",
			"Min count",
			"Max count",
			"Active",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Name,
				res[i].Description,
				fmt.Sprint(res[i].MinCount),
				fmt.Sprint(res[i].MaxCount),
				fmt.Sprint(res[i].Active),
			},
		})
	}

	return list, err
}

func (h *Handler) TransportGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Transport.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("name", entity.Name)
	v.Set("description", entity.Description)
	v.Set("min_count", fmt.Sprint(entity.MinCount))
	v.Set("max_count", fmt.Sprint(entity.MaxCount))
	v.Set("active", fmt.Sprint(entity.Active))
	return v, err
}

func (h *Handler) TripCreate(ctx echo.Context) error {
	var payload Trip
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.Trip.Create()
	op.SetName(payload.Name)
	op.SetDescription(payload.Description)
	op.SetComment(payload.Comment)
	op.SetDuration(payload.Duration)
	op.SetActive(payload.Active)
	op.SetBegin(payload.Begin)
	op.SetEnd(payload.End)
	op.SetPhoto(payload.Photo)
	op.SetType(payload.Type)
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) TripUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.Trip.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload Trip
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetName(payload.Name)
	op.SetDescription(payload.Description)
	op.SetComment(payload.Comment)
	op.SetDuration(payload.Duration)
	op.SetActive(payload.Active)
	op.SetBegin(payload.Begin)
	op.SetEnd(payload.End)
	op.SetPhoto(payload.Photo)
	op.SetType(payload.Type)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) TripDelete(ctx echo.Context, id int) error {
	return h.client.Trip.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) TripList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.Trip.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(trip.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Name",
			"Description",
			"Comment",
			"Duration",
			"Active",
			"Begin",
			"End",
			"Photo",
			"Type",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Name,
				res[i].Description,
				res[i].Comment,
				res[i].Duration.Format(h.Config.TimeFormat),
				fmt.Sprint(res[i].Active),
				res[i].Begin.Format(h.Config.TimeFormat),
				res[i].End.Format(h.Config.TimeFormat),
				res[i].Photo,
				fmt.Sprint(res[i].Type),
			},
		})
	}

	return list, err
}

func (h *Handler) TripGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.Trip.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("name", entity.Name)
	v.Set("description", entity.Description)
	v.Set("comment", entity.Comment)
	v.Set("duration", entity.Duration.Format(dateTimeFormat))
	v.Set("active", fmt.Sprint(entity.Active))
	v.Set("begin", entity.Begin.Format(dateTimeFormat))
	v.Set("end", entity.End.Format(dateTimeFormat))
	v.Set("photo", entity.Photo)
	v.Set("type", fmt.Sprint(entity.Type))
	return v, err
}

func (h *Handler) UserCreate(ctx echo.Context) error {
	var payload User
	if err := h.bind(ctx, &payload); err != nil {
		return err
	}

	op := h.client.User.Create()
	op.SetName(payload.Name)
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	if payload.CreatedAt != nil {
		op.SetCreatedAt(*payload.CreatedAt)
	}
	_, err := op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserUpdate(ctx echo.Context, id int) error {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return err
	}

	var payload User
	if err = h.bind(ctx, &payload); err != nil {
		return err
	}

	op := entity.Update()
	op.SetName(payload.Name)
	op.SetEmail(payload.Email)
	if payload.Password != nil {
		op.SetPassword(*payload.Password)
	}
	op.SetVerified(payload.Verified)
	op.SetAdmin(payload.Admin)
	_, err = op.Save(ctx.Request().Context())
	return err
}

func (h *Handler) UserDelete(ctx echo.Context, id int) error {
	return h.client.User.DeleteOneID(id).
		Exec(ctx.Request().Context())
}

func (h *Handler) UserList(ctx echo.Context) (*EntityList, error) {
	page, offset := h.getPageAndOffset(ctx)
	res, err := h.client.User.
		Query().
		Limit(h.Config.ItemsPerPage + 1).
		Offset(offset).
		Order(user.ByID(sql.OrderDesc())).
		All(ctx.Request().Context())

	if err != nil {
		return nil, err
	}

	list := &EntityList{
		Columns: []string{
			"Name",
			"Email",
			"Verified",
			"Admin",
			"Created at",
		},
		Entities:    make([]EntityValues, 0, len(res)),
		Page:        page,
		HasNextPage: len(res) > h.Config.ItemsPerPage,
	}

	for i := 0; i <= len(res)-1; i++ {
		list.Entities = append(list.Entities, EntityValues{
			ID: res[i].ID,
			Values: []string{
				res[i].Name,
				res[i].Email,
				fmt.Sprint(res[i].Verified),
				fmt.Sprint(res[i].Admin),
				res[i].CreatedAt.Format(h.Config.TimeFormat),
			},
		})
	}

	return list, err
}

func (h *Handler) UserGet(ctx echo.Context, id int) (url.Values, error) {
	entity, err := h.client.User.Get(ctx.Request().Context(), id)
	if err != nil {
		return nil, err
	}

	v := url.Values{}
	v.Set("name", entity.Name)
	v.Set("email", entity.Email)
	v.Set("verified", fmt.Sprint(entity.Verified))
	v.Set("admin", fmt.Sprint(entity.Admin))
	return v, err
}

func (h *Handler) getPageAndOffset(ctx echo.Context) (int, int) {
	if page, err := strconv.Atoi(ctx.QueryParam(h.Config.PageQueryKey)); err == nil {
		if page > 1 {
			return page, (page - 1) * h.Config.ItemsPerPage
		}
	}
	return 1, 0
}

func (h *Handler) bind(ctx echo.Context, entity any) error {
	// Echo requires some pre-processing of form values to avoid problems.
	for k, v := range ctx.Request().Form {
		// Remove empty field values so Echo's bind does not fail when trying to parse things like
		// times, etc.
		if len(v) == 1 && len(v[0]) == 0 {
			delete(ctx.Request().Form, k)
			continue
		}

		// Echo expects datetime values to be in a certain format but that does not align with the datetime-local
		// HTML form element format, so we will attempt to convert it here.
		for _, format := range []string{dateTimeFormatNoSeconds, dateTimeFormat} {
			if t, err := time.Parse(format, v[0]); err == nil {
				ctx.Request().Form[k][0] = t.Format(time.RFC3339)
				break
			}
		}
	}
	return ctx.Bind(entity)
}
