// Code generated by ent, DO NOT EDIT.
package admin

import (
	"entgo.io/ent/schema/field"
)

type Enum struct {
	Label, Value string
}

type FieldSchema struct {
	Name      string
	Type      field.Type
	Optional  bool
	Immutable bool
	Sensitive bool
	Enums     []string
}

const NameCustomer = "Customer"

var fieldsCustomer = []*FieldSchema{
	{
		Name:      "firstname",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "lastname",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "phone",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "active",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "email",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "password",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_by",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameGLog = "GLog"

var fieldsGLog = []*FieldSchema{
	{
		Name:      "action",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_by",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameGOrder = "GOrder"

var fieldsGOrder = []*FieldSchema{
	{
		Name:      "num",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "trip_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "count_person",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "day",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "begin",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "transport_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "guide_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "cost",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "status",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "pay_status",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "paid_sum",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "customer_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "place",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "updated",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_by",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "archived",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameGuide = "Guide"

var fieldsGuide = []*FieldSchema{
	{
		Name:      "firstname",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "lastname",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "phone",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "active",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameOrderNumber = "OrderNumber"

var fieldsOrderNumber = []*FieldSchema{
	{
		Name:      "num",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NamePasswordToken = "PasswordToken"

var fieldsPasswordToken = []*FieldSchema{
	{
		Name:      "token",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: true,
		Enums:     nil,
	},
	{
		Name:      "user_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameShedule = "Shedule"

var fieldsShedule = []*FieldSchema{
	{
		Name:      "resource_type",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "resource_id",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "begin",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "end",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameTransport = "Transport"

var fieldsTransport = []*FieldSchema{
	{
		Name:      "name",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "description",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "min_count",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "max_count",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "active",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameTrip = "Trip"

var fieldsTrip = []*FieldSchema{
	{
		Name:      "name",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "description",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "comment",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "duration",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "active",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "begin",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "end",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "photo",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "type",
		Type:      field.TypeInt,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
}

const NameUser = "User"

var fieldsUser = []*FieldSchema{
	{
		Name:      "name",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "email",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "password",
		Type:      field.TypeString,
		Optional:  false,
		Immutable: false,
		Sensitive: true,
		Enums:     nil,
	},
	{
		Name:      "verified",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "admin",
		Type:      field.TypeBool,
		Optional:  false,
		Immutable: false,
		Sensitive: false,
		Enums:     nil,
	},
	{
		Name:      "created_at",
		Type:      field.TypeTime,
		Optional:  false,
		Immutable: true,
		Sensitive: false,
		Enums:     nil,
	},
}
