// Code generated by ent, DO NOT EDIT.
package admin

import "time"

type Cost struct {
	Cost        *int `form:"cost"`
	TripID      *int `form:"trip_id"`
	TransportID *int `form:"transport_id"`
}

func (e *Cost) GetName() string {
	return NameCost
}

func (e *Cost) GetSchema() []*FieldSchema {
	return fieldsCost
}

type Customer struct {
	Firstname string     `form:"firstname"`
	Lastname  string     `form:"lastname"`
	Phone     string     `form:"phone"`
	Comment   string     `form:"comment"`
	Active    bool       `form:"active"`
	Email     string     `form:"email"`
	Password  string     `form:"password"`
	Created   *time.Time `form:"created"`
	Updated   *time.Time `form:"updated"`
	CreatedBy *int       `form:"created_by"`
}

func (e *Customer) GetName() string {
	return NameCustomer
}

func (e *Customer) GetSchema() []*FieldSchema {
	return fieldsCustomer
}

type GLog struct {
	Action    string     `form:"action"`
	Comment   string     `form:"comment"`
	Created   *time.Time `form:"created"`
	CreatedBy *int       `form:"created_by"`
}

func (e *GLog) GetName() string {
	return NameGLog
}

func (e *GLog) GetSchema() []*FieldSchema {
	return fieldsGLog
}

type GOrder struct {
	Num          *int       `form:"num"`
	TripID       *int       `form:"trip_id"`
	TouristCount *int       `form:"tourist_count"`
	Day          time.Time  `form:"day"`
	Begin        time.Time  `form:"begin"`
	TransportID  *int       `form:"transport_id"`
	GuideID      *int       `form:"guide_id"`
	Cost         *int       `form:"cost"`
	Status       *int       `form:"status"`
	PayStatus    *int       `form:"pay_status"`
	PaidSum      *int       `form:"paid_sum"`
	CustomerID   *int       `form:"customer_id"`
	Place        string     `form:"place"`
	Comment      string     `form:"comment"`
	Created      *time.Time `form:"created"`
	Updated      *time.Time `form:"updated"`
	CreatedBy    *int       `form:"created_by"`
	Archived     bool       `form:"archived"`
}

func (e *GOrder) GetName() string {
	return NameGOrder
}

func (e *GOrder) GetSchema() []*FieldSchema {
	return fieldsGOrder
}

type Guide struct {
	Firstname string `form:"firstname"`
	Lastname  string `form:"lastname"`
	Phone     string `form:"phone"`
	Comment   string `form:"comment"`
	Active    bool   `form:"active"`
}

func (e *Guide) GetName() string {
	return NameGuide
}

func (e *Guide) GetSchema() []*FieldSchema {
	return fieldsGuide
}

type OrderNumber struct {
	Num *int `form:"num"`
}

func (e *OrderNumber) GetName() string {
	return NameOrderNumber
}

func (e *OrderNumber) GetSchema() []*FieldSchema {
	return fieldsOrderNumber
}

type PasswordToken struct {
	Token     *string    `form:"token"`
	UserID    int        `form:"user_id"`
	CreatedAt *time.Time `form:"created_at"`
}

func (e *PasswordToken) GetName() string {
	return NamePasswordToken
}

func (e *PasswordToken) GetSchema() []*FieldSchema {
	return fieldsPasswordToken
}

type Shedule struct {
	ResourceType int       `form:"resource_type"`
	ResourceID   int       `form:"resource_id"`
	Begin        time.Time `form:"begin"`
	End          time.Time `form:"end"`
	Comment      *string   `form:"comment"`
}

func (e *Shedule) GetName() string {
	return NameShedule
}

func (e *Shedule) GetSchema() []*FieldSchema {
	return fieldsShedule
}

type Transport struct {
	Name        string `form:"name"`
	Description string `form:"description"`
	MinCount    *int   `form:"min_count"`
	MaxCount    *int   `form:"max_count"`
	Active      bool   `form:"active"`
}

func (e *Transport) GetName() string {
	return NameTransport
}

func (e *Transport) GetSchema() []*FieldSchema {
	return fieldsTransport
}

type Trip struct {
	Name        string    `form:"name"`
	Description string    `form:"description"`
	Comment     string    `form:"comment"`
	Duration    time.Time `form:"duration"`
	Active      bool      `form:"active"`
	Begin       time.Time `form:"begin"`
	End         time.Time `form:"end"`
	Photo       string    `form:"photo"`
	Type        int       `form:"type"`
}

func (e *Trip) GetName() string {
	return NameTrip
}

func (e *Trip) GetSchema() []*FieldSchema {
	return fieldsTrip
}

type User struct {
	Name      string     `form:"name"`
	Email     string     `form:"email"`
	Password  *string    `form:"password"`
	Verified  bool       `form:"verified"`
	Admin     bool       `form:"admin"`
	CreatedAt *time.Time `form:"created_at"`
}

func (e *User) GetName() string {
	return NameUser
}

func (e *User) GetSchema() []*FieldSchema {
	return fieldsUser
}

type EntityType interface {
	GetName() string
	GetSchema() []*FieldSchema
}

var entityTypes = []EntityType{
	&Cost{},
	&Customer{},
	&GLog{},
	&GOrder{},
	&Guide{},
	&OrderNumber{},
	&PasswordToken{},
	&Shedule{},
	&Transport{},
	&Trip{},
	&User{},
}

type EntityList struct {
	Columns     []string
	Entities    []EntityValues
	Page        int
	HasNextPage bool
}

type EntityValues struct {
	ID     int
	Values []string
}

type HandlerConfig struct {
	ItemsPerPage int
	PageQueryKey string
	TimeFormat   string
}

func GetEntityTypes() []EntityType {
	return entityTypes
}
