// Code generated by ent, DO NOT EDIT.

package ordernumber

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ordernumber type in the database.
	Label = "order_number"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNum holds the string denoting the num field in the database.
	FieldNum = "num"
	// Table holds the table name of the ordernumber in the database.
	Table = "order_numbers"
)

// Columns holds all SQL columns for ordernumber fields.
var Columns = []string{
	FieldID,
	FieldNum,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNum holds the default value on creation for the "num" field.
	DefaultNum int
)

// OrderOption defines the ordering options for the OrderNumber queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNum orders the results by the num field.
func ByNum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNum, opts...).ToFunc()
}
