// Code generated by ent, DO NOT EDIT.

package ordernumber

import (
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldLTE(FieldID, id))
}

// Num applies equality check predicate on the "num" field. It's identical to NumEQ.
func Num(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldEQ(FieldNum, v))
}

// NumEQ applies the EQ predicate on the "num" field.
func NumEQ(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldEQ(FieldNum, v))
}

// NumNEQ applies the NEQ predicate on the "num" field.
func NumNEQ(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldNEQ(FieldNum, v))
}

// NumIn applies the In predicate on the "num" field.
func NumIn(vs ...int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldIn(FieldNum, vs...))
}

// NumNotIn applies the NotIn predicate on the "num" field.
func NumNotIn(vs ...int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldNotIn(FieldNum, vs...))
}

// NumGT applies the GT predicate on the "num" field.
func NumGT(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldGT(FieldNum, v))
}

// NumGTE applies the GTE predicate on the "num" field.
func NumGTE(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldGTE(FieldNum, v))
}

// NumLT applies the LT predicate on the "num" field.
func NumLT(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldLT(FieldNum, v))
}

// NumLTE applies the LTE predicate on the "num" field.
func NumLTE(v int) predicate.OrderNumber {
	return predicate.OrderNumber(sql.FieldLTE(FieldNum, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderNumber) predicate.OrderNumber {
	return predicate.OrderNumber(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderNumber) predicate.OrderNumber {
	return predicate.OrderNumber(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderNumber) predicate.OrderNumber {
	return predicate.OrderNumber(sql.NotPredicates(p))
}
