// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/mikestefanello/pagoda/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mikestefanello/pagoda/ent/cost"
	"github.com/mikestefanello/pagoda/ent/customer"
	"github.com/mikestefanello/pagoda/ent/glog"
	"github.com/mikestefanello/pagoda/ent/gorder"
	"github.com/mikestefanello/pagoda/ent/guide"
	"github.com/mikestefanello/pagoda/ent/ordernumber"
	"github.com/mikestefanello/pagoda/ent/passwordtoken"
	"github.com/mikestefanello/pagoda/ent/shedule"
	"github.com/mikestefanello/pagoda/ent/transport"
	"github.com/mikestefanello/pagoda/ent/trip"
	"github.com/mikestefanello/pagoda/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Cost is the client for interacting with the Cost builders.
	Cost *CostClient
	// Customer is the client for interacting with the Customer builders.
	Customer *CustomerClient
	// GLog is the client for interacting with the GLog builders.
	GLog *GLogClient
	// GOrder is the client for interacting with the GOrder builders.
	GOrder *GOrderClient
	// Guide is the client for interacting with the Guide builders.
	Guide *GuideClient
	// OrderNumber is the client for interacting with the OrderNumber builders.
	OrderNumber *OrderNumberClient
	// PasswordToken is the client for interacting with the PasswordToken builders.
	PasswordToken *PasswordTokenClient
	// Shedule is the client for interacting with the Shedule builders.
	Shedule *SheduleClient
	// Transport is the client for interacting with the Transport builders.
	Transport *TransportClient
	// Trip is the client for interacting with the Trip builders.
	Trip *TripClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Cost = NewCostClient(c.config)
	c.Customer = NewCustomerClient(c.config)
	c.GLog = NewGLogClient(c.config)
	c.GOrder = NewGOrderClient(c.config)
	c.Guide = NewGuideClient(c.config)
	c.OrderNumber = NewOrderNumberClient(c.config)
	c.PasswordToken = NewPasswordTokenClient(c.config)
	c.Shedule = NewSheduleClient(c.config)
	c.Transport = NewTransportClient(c.config)
	c.Trip = NewTripClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Cost:          NewCostClient(cfg),
		Customer:      NewCustomerClient(cfg),
		GLog:          NewGLogClient(cfg),
		GOrder:        NewGOrderClient(cfg),
		Guide:         NewGuideClient(cfg),
		OrderNumber:   NewOrderNumberClient(cfg),
		PasswordToken: NewPasswordTokenClient(cfg),
		Shedule:       NewSheduleClient(cfg),
		Transport:     NewTransportClient(cfg),
		Trip:          NewTripClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Cost:          NewCostClient(cfg),
		Customer:      NewCustomerClient(cfg),
		GLog:          NewGLogClient(cfg),
		GOrder:        NewGOrderClient(cfg),
		Guide:         NewGuideClient(cfg),
		OrderNumber:   NewOrderNumberClient(cfg),
		PasswordToken: NewPasswordTokenClient(cfg),
		Shedule:       NewSheduleClient(cfg),
		Transport:     NewTransportClient(cfg),
		Trip:          NewTripClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Cost.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Cost, c.Customer, c.GLog, c.GOrder, c.Guide, c.OrderNumber, c.PasswordToken,
		c.Shedule, c.Transport, c.Trip, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Cost, c.Customer, c.GLog, c.GOrder, c.Guide, c.OrderNumber, c.PasswordToken,
		c.Shedule, c.Transport, c.Trip, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CostMutation:
		return c.Cost.mutate(ctx, m)
	case *CustomerMutation:
		return c.Customer.mutate(ctx, m)
	case *GLogMutation:
		return c.GLog.mutate(ctx, m)
	case *GOrderMutation:
		return c.GOrder.mutate(ctx, m)
	case *GuideMutation:
		return c.Guide.mutate(ctx, m)
	case *OrderNumberMutation:
		return c.OrderNumber.mutate(ctx, m)
	case *PasswordTokenMutation:
		return c.PasswordToken.mutate(ctx, m)
	case *SheduleMutation:
		return c.Shedule.mutate(ctx, m)
	case *TransportMutation:
		return c.Transport.mutate(ctx, m)
	case *TripMutation:
		return c.Trip.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CostClient is a client for the Cost schema.
type CostClient struct {
	config
}

// NewCostClient returns a client for the Cost from the given config.
func NewCostClient(c config) *CostClient {
	return &CostClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `cost.Hooks(f(g(h())))`.
func (c *CostClient) Use(hooks ...Hook) {
	c.hooks.Cost = append(c.hooks.Cost, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `cost.Intercept(f(g(h())))`.
func (c *CostClient) Intercept(interceptors ...Interceptor) {
	c.inters.Cost = append(c.inters.Cost, interceptors...)
}

// Create returns a builder for creating a Cost entity.
func (c *CostClient) Create() *CostCreate {
	mutation := newCostMutation(c.config, OpCreate)
	return &CostCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Cost entities.
func (c *CostClient) CreateBulk(builders ...*CostCreate) *CostCreateBulk {
	return &CostCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CostClient) MapCreateBulk(slice any, setFunc func(*CostCreate, int)) *CostCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CostCreateBulk{err: fmt.Errorf("calling to CostClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CostCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CostCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Cost.
func (c *CostClient) Update() *CostUpdate {
	mutation := newCostMutation(c.config, OpUpdate)
	return &CostUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CostClient) UpdateOne(_m *Cost) *CostUpdateOne {
	mutation := newCostMutation(c.config, OpUpdateOne, withCost(_m))
	return &CostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CostClient) UpdateOneID(id int) *CostUpdateOne {
	mutation := newCostMutation(c.config, OpUpdateOne, withCostID(id))
	return &CostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Cost.
func (c *CostClient) Delete() *CostDelete {
	mutation := newCostMutation(c.config, OpDelete)
	return &CostDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CostClient) DeleteOne(_m *Cost) *CostDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CostClient) DeleteOneID(id int) *CostDeleteOne {
	builder := c.Delete().Where(cost.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CostDeleteOne{builder}
}

// Query returns a query builder for Cost.
func (c *CostClient) Query() *CostQuery {
	return &CostQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCost},
		inters: c.Interceptors(),
	}
}

// Get returns a Cost entity by its id.
func (c *CostClient) Get(ctx context.Context, id int) (*Cost, error) {
	return c.Query().Where(cost.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CostClient) GetX(ctx context.Context, id int) *Cost {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CostClient) Hooks() []Hook {
	return c.hooks.Cost
}

// Interceptors returns the client interceptors.
func (c *CostClient) Interceptors() []Interceptor {
	return c.inters.Cost
}

func (c *CostClient) mutate(ctx context.Context, m *CostMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CostCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CostUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CostUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CostDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Cost mutation op: %q", m.Op())
	}
}

// CustomerClient is a client for the Customer schema.
type CustomerClient struct {
	config
}

// NewCustomerClient returns a client for the Customer from the given config.
func NewCustomerClient(c config) *CustomerClient {
	return &CustomerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customer.Hooks(f(g(h())))`.
func (c *CustomerClient) Use(hooks ...Hook) {
	c.hooks.Customer = append(c.hooks.Customer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customer.Intercept(f(g(h())))`.
func (c *CustomerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Customer = append(c.inters.Customer, interceptors...)
}

// Create returns a builder for creating a Customer entity.
func (c *CustomerClient) Create() *CustomerCreate {
	mutation := newCustomerMutation(c.config, OpCreate)
	return &CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Customer entities.
func (c *CustomerClient) CreateBulk(builders ...*CustomerCreate) *CustomerCreateBulk {
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerClient) MapCreateBulk(slice any, setFunc func(*CustomerCreate, int)) *CustomerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerCreateBulk{err: fmt.Errorf("calling to CustomerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Customer.
func (c *CustomerClient) Update() *CustomerUpdate {
	mutation := newCustomerMutation(c.config, OpUpdate)
	return &CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerClient) UpdateOne(_m *Customer) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomer(_m))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerClient) UpdateOneID(id int) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomerID(id))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Customer.
func (c *CustomerClient) Delete() *CustomerDelete {
	mutation := newCustomerMutation(c.config, OpDelete)
	return &CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerClient) DeleteOne(_m *Customer) *CustomerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerClient) DeleteOneID(id int) *CustomerDeleteOne {
	builder := c.Delete().Where(customer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerDeleteOne{builder}
}

// Query returns a query builder for Customer.
func (c *CustomerClient) Query() *CustomerQuery {
	return &CustomerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomer},
		inters: c.Interceptors(),
	}
}

// Get returns a Customer entity by its id.
func (c *CustomerClient) Get(ctx context.Context, id int) (*Customer, error) {
	return c.Query().Where(customer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerClient) GetX(ctx context.Context, id int) *Customer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CustomerClient) Hooks() []Hook {
	return c.hooks.Customer
}

// Interceptors returns the client interceptors.
func (c *CustomerClient) Interceptors() []Interceptor {
	return c.inters.Customer
}

func (c *CustomerClient) mutate(ctx context.Context, m *CustomerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Customer mutation op: %q", m.Op())
	}
}

// GLogClient is a client for the GLog schema.
type GLogClient struct {
	config
}

// NewGLogClient returns a client for the GLog from the given config.
func NewGLogClient(c config) *GLogClient {
	return &GLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `glog.Hooks(f(g(h())))`.
func (c *GLogClient) Use(hooks ...Hook) {
	c.hooks.GLog = append(c.hooks.GLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `glog.Intercept(f(g(h())))`.
func (c *GLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.GLog = append(c.inters.GLog, interceptors...)
}

// Create returns a builder for creating a GLog entity.
func (c *GLogClient) Create() *GLogCreate {
	mutation := newGLogMutation(c.config, OpCreate)
	return &GLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GLog entities.
func (c *GLogClient) CreateBulk(builders ...*GLogCreate) *GLogCreateBulk {
	return &GLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GLogClient) MapCreateBulk(slice any, setFunc func(*GLogCreate, int)) *GLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GLogCreateBulk{err: fmt.Errorf("calling to GLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GLog.
func (c *GLogClient) Update() *GLogUpdate {
	mutation := newGLogMutation(c.config, OpUpdate)
	return &GLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GLogClient) UpdateOne(_m *GLog) *GLogUpdateOne {
	mutation := newGLogMutation(c.config, OpUpdateOne, withGLog(_m))
	return &GLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GLogClient) UpdateOneID(id int) *GLogUpdateOne {
	mutation := newGLogMutation(c.config, OpUpdateOne, withGLogID(id))
	return &GLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GLog.
func (c *GLogClient) Delete() *GLogDelete {
	mutation := newGLogMutation(c.config, OpDelete)
	return &GLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GLogClient) DeleteOne(_m *GLog) *GLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GLogClient) DeleteOneID(id int) *GLogDeleteOne {
	builder := c.Delete().Where(glog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GLogDeleteOne{builder}
}

// Query returns a query builder for GLog.
func (c *GLogClient) Query() *GLogQuery {
	return &GLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGLog},
		inters: c.Interceptors(),
	}
}

// Get returns a GLog entity by its id.
func (c *GLogClient) Get(ctx context.Context, id int) (*GLog, error) {
	return c.Query().Where(glog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GLogClient) GetX(ctx context.Context, id int) *GLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GLogClient) Hooks() []Hook {
	return c.hooks.GLog
}

// Interceptors returns the client interceptors.
func (c *GLogClient) Interceptors() []Interceptor {
	return c.inters.GLog
}

func (c *GLogClient) mutate(ctx context.Context, m *GLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GLog mutation op: %q", m.Op())
	}
}

// GOrderClient is a client for the GOrder schema.
type GOrderClient struct {
	config
}

// NewGOrderClient returns a client for the GOrder from the given config.
func NewGOrderClient(c config) *GOrderClient {
	return &GOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gorder.Hooks(f(g(h())))`.
func (c *GOrderClient) Use(hooks ...Hook) {
	c.hooks.GOrder = append(c.hooks.GOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gorder.Intercept(f(g(h())))`.
func (c *GOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.GOrder = append(c.inters.GOrder, interceptors...)
}

// Create returns a builder for creating a GOrder entity.
func (c *GOrderClient) Create() *GOrderCreate {
	mutation := newGOrderMutation(c.config, OpCreate)
	return &GOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GOrder entities.
func (c *GOrderClient) CreateBulk(builders ...*GOrderCreate) *GOrderCreateBulk {
	return &GOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GOrderClient) MapCreateBulk(slice any, setFunc func(*GOrderCreate, int)) *GOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GOrderCreateBulk{err: fmt.Errorf("calling to GOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GOrder.
func (c *GOrderClient) Update() *GOrderUpdate {
	mutation := newGOrderMutation(c.config, OpUpdate)
	return &GOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GOrderClient) UpdateOne(_m *GOrder) *GOrderUpdateOne {
	mutation := newGOrderMutation(c.config, OpUpdateOne, withGOrder(_m))
	return &GOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GOrderClient) UpdateOneID(id int) *GOrderUpdateOne {
	mutation := newGOrderMutation(c.config, OpUpdateOne, withGOrderID(id))
	return &GOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GOrder.
func (c *GOrderClient) Delete() *GOrderDelete {
	mutation := newGOrderMutation(c.config, OpDelete)
	return &GOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GOrderClient) DeleteOne(_m *GOrder) *GOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GOrderClient) DeleteOneID(id int) *GOrderDeleteOne {
	builder := c.Delete().Where(gorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GOrderDeleteOne{builder}
}

// Query returns a query builder for GOrder.
func (c *GOrderClient) Query() *GOrderQuery {
	return &GOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a GOrder entity by its id.
func (c *GOrderClient) Get(ctx context.Context, id int) (*GOrder, error) {
	return c.Query().Where(gorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GOrderClient) GetX(ctx context.Context, id int) *GOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GOrderClient) Hooks() []Hook {
	return c.hooks.GOrder
}

// Interceptors returns the client interceptors.
func (c *GOrderClient) Interceptors() []Interceptor {
	return c.inters.GOrder
}

func (c *GOrderClient) mutate(ctx context.Context, m *GOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GOrder mutation op: %q", m.Op())
	}
}

// GuideClient is a client for the Guide schema.
type GuideClient struct {
	config
}

// NewGuideClient returns a client for the Guide from the given config.
func NewGuideClient(c config) *GuideClient {
	return &GuideClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `guide.Hooks(f(g(h())))`.
func (c *GuideClient) Use(hooks ...Hook) {
	c.hooks.Guide = append(c.hooks.Guide, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `guide.Intercept(f(g(h())))`.
func (c *GuideClient) Intercept(interceptors ...Interceptor) {
	c.inters.Guide = append(c.inters.Guide, interceptors...)
}

// Create returns a builder for creating a Guide entity.
func (c *GuideClient) Create() *GuideCreate {
	mutation := newGuideMutation(c.config, OpCreate)
	return &GuideCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Guide entities.
func (c *GuideClient) CreateBulk(builders ...*GuideCreate) *GuideCreateBulk {
	return &GuideCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GuideClient) MapCreateBulk(slice any, setFunc func(*GuideCreate, int)) *GuideCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GuideCreateBulk{err: fmt.Errorf("calling to GuideClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GuideCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GuideCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Guide.
func (c *GuideClient) Update() *GuideUpdate {
	mutation := newGuideMutation(c.config, OpUpdate)
	return &GuideUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GuideClient) UpdateOne(_m *Guide) *GuideUpdateOne {
	mutation := newGuideMutation(c.config, OpUpdateOne, withGuide(_m))
	return &GuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GuideClient) UpdateOneID(id int) *GuideUpdateOne {
	mutation := newGuideMutation(c.config, OpUpdateOne, withGuideID(id))
	return &GuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Guide.
func (c *GuideClient) Delete() *GuideDelete {
	mutation := newGuideMutation(c.config, OpDelete)
	return &GuideDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GuideClient) DeleteOne(_m *Guide) *GuideDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GuideClient) DeleteOneID(id int) *GuideDeleteOne {
	builder := c.Delete().Where(guide.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GuideDeleteOne{builder}
}

// Query returns a query builder for Guide.
func (c *GuideClient) Query() *GuideQuery {
	return &GuideQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGuide},
		inters: c.Interceptors(),
	}
}

// Get returns a Guide entity by its id.
func (c *GuideClient) Get(ctx context.Context, id int) (*Guide, error) {
	return c.Query().Where(guide.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GuideClient) GetX(ctx context.Context, id int) *Guide {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GuideClient) Hooks() []Hook {
	return c.hooks.Guide
}

// Interceptors returns the client interceptors.
func (c *GuideClient) Interceptors() []Interceptor {
	return c.inters.Guide
}

func (c *GuideClient) mutate(ctx context.Context, m *GuideMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GuideCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GuideUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GuideUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GuideDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Guide mutation op: %q", m.Op())
	}
}

// OrderNumberClient is a client for the OrderNumber schema.
type OrderNumberClient struct {
	config
}

// NewOrderNumberClient returns a client for the OrderNumber from the given config.
func NewOrderNumberClient(c config) *OrderNumberClient {
	return &OrderNumberClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ordernumber.Hooks(f(g(h())))`.
func (c *OrderNumberClient) Use(hooks ...Hook) {
	c.hooks.OrderNumber = append(c.hooks.OrderNumber, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ordernumber.Intercept(f(g(h())))`.
func (c *OrderNumberClient) Intercept(interceptors ...Interceptor) {
	c.inters.OrderNumber = append(c.inters.OrderNumber, interceptors...)
}

// Create returns a builder for creating a OrderNumber entity.
func (c *OrderNumberClient) Create() *OrderNumberCreate {
	mutation := newOrderNumberMutation(c.config, OpCreate)
	return &OrderNumberCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OrderNumber entities.
func (c *OrderNumberClient) CreateBulk(builders ...*OrderNumberCreate) *OrderNumberCreateBulk {
	return &OrderNumberCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderNumberClient) MapCreateBulk(slice any, setFunc func(*OrderNumberCreate, int)) *OrderNumberCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderNumberCreateBulk{err: fmt.Errorf("calling to OrderNumberClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderNumberCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderNumberCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OrderNumber.
func (c *OrderNumberClient) Update() *OrderNumberUpdate {
	mutation := newOrderNumberMutation(c.config, OpUpdate)
	return &OrderNumberUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderNumberClient) UpdateOne(_m *OrderNumber) *OrderNumberUpdateOne {
	mutation := newOrderNumberMutation(c.config, OpUpdateOne, withOrderNumber(_m))
	return &OrderNumberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderNumberClient) UpdateOneID(id int) *OrderNumberUpdateOne {
	mutation := newOrderNumberMutation(c.config, OpUpdateOne, withOrderNumberID(id))
	return &OrderNumberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OrderNumber.
func (c *OrderNumberClient) Delete() *OrderNumberDelete {
	mutation := newOrderNumberMutation(c.config, OpDelete)
	return &OrderNumberDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderNumberClient) DeleteOne(_m *OrderNumber) *OrderNumberDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderNumberClient) DeleteOneID(id int) *OrderNumberDeleteOne {
	builder := c.Delete().Where(ordernumber.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderNumberDeleteOne{builder}
}

// Query returns a query builder for OrderNumber.
func (c *OrderNumberClient) Query() *OrderNumberQuery {
	return &OrderNumberQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrderNumber},
		inters: c.Interceptors(),
	}
}

// Get returns a OrderNumber entity by its id.
func (c *OrderNumberClient) Get(ctx context.Context, id int) (*OrderNumber, error) {
	return c.Query().Where(ordernumber.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderNumberClient) GetX(ctx context.Context, id int) *OrderNumber {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OrderNumberClient) Hooks() []Hook {
	return c.hooks.OrderNumber
}

// Interceptors returns the client interceptors.
func (c *OrderNumberClient) Interceptors() []Interceptor {
	return c.inters.OrderNumber
}

func (c *OrderNumberClient) mutate(ctx context.Context, m *OrderNumberMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderNumberCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderNumberUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderNumberUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderNumberDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OrderNumber mutation op: %q", m.Op())
	}
}

// PasswordTokenClient is a client for the PasswordToken schema.
type PasswordTokenClient struct {
	config
}

// NewPasswordTokenClient returns a client for the PasswordToken from the given config.
func NewPasswordTokenClient(c config) *PasswordTokenClient {
	return &PasswordTokenClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passwordtoken.Hooks(f(g(h())))`.
func (c *PasswordTokenClient) Use(hooks ...Hook) {
	c.hooks.PasswordToken = append(c.hooks.PasswordToken, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passwordtoken.Intercept(f(g(h())))`.
func (c *PasswordTokenClient) Intercept(interceptors ...Interceptor) {
	c.inters.PasswordToken = append(c.inters.PasswordToken, interceptors...)
}

// Create returns a builder for creating a PasswordToken entity.
func (c *PasswordTokenClient) Create() *PasswordTokenCreate {
	mutation := newPasswordTokenMutation(c.config, OpCreate)
	return &PasswordTokenCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasswordToken entities.
func (c *PasswordTokenClient) CreateBulk(builders ...*PasswordTokenCreate) *PasswordTokenCreateBulk {
	return &PasswordTokenCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PasswordTokenClient) MapCreateBulk(slice any, setFunc func(*PasswordTokenCreate, int)) *PasswordTokenCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PasswordTokenCreateBulk{err: fmt.Errorf("calling to PasswordTokenClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PasswordTokenCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PasswordTokenCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasswordToken.
func (c *PasswordTokenClient) Update() *PasswordTokenUpdate {
	mutation := newPasswordTokenMutation(c.config, OpUpdate)
	return &PasswordTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasswordTokenClient) UpdateOne(_m *PasswordToken) *PasswordTokenUpdateOne {
	mutation := newPasswordTokenMutation(c.config, OpUpdateOne, withPasswordToken(_m))
	return &PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasswordTokenClient) UpdateOneID(id int) *PasswordTokenUpdateOne {
	mutation := newPasswordTokenMutation(c.config, OpUpdateOne, withPasswordTokenID(id))
	return &PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasswordToken.
func (c *PasswordTokenClient) Delete() *PasswordTokenDelete {
	mutation := newPasswordTokenMutation(c.config, OpDelete)
	return &PasswordTokenDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasswordTokenClient) DeleteOne(_m *PasswordToken) *PasswordTokenDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasswordTokenClient) DeleteOneID(id int) *PasswordTokenDeleteOne {
	builder := c.Delete().Where(passwordtoken.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasswordTokenDeleteOne{builder}
}

// Query returns a query builder for PasswordToken.
func (c *PasswordTokenClient) Query() *PasswordTokenQuery {
	return &PasswordTokenQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePasswordToken},
		inters: c.Interceptors(),
	}
}

// Get returns a PasswordToken entity by its id.
func (c *PasswordTokenClient) Get(ctx context.Context, id int) (*PasswordToken, error) {
	return c.Query().Where(passwordtoken.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasswordTokenClient) GetX(ctx context.Context, id int) *PasswordToken {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a PasswordToken.
func (c *PasswordTokenClient) QueryUser(_m *PasswordToken) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(passwordtoken.Table, passwordtoken.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, passwordtoken.UserTable, passwordtoken.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PasswordTokenClient) Hooks() []Hook {
	hooks := c.hooks.PasswordToken
	return append(hooks[:len(hooks):len(hooks)], passwordtoken.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *PasswordTokenClient) Interceptors() []Interceptor {
	return c.inters.PasswordToken
}

func (c *PasswordTokenClient) mutate(ctx context.Context, m *PasswordTokenMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PasswordTokenCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PasswordTokenUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PasswordTokenUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PasswordTokenDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PasswordToken mutation op: %q", m.Op())
	}
}

// SheduleClient is a client for the Shedule schema.
type SheduleClient struct {
	config
}

// NewSheduleClient returns a client for the Shedule from the given config.
func NewSheduleClient(c config) *SheduleClient {
	return &SheduleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `shedule.Hooks(f(g(h())))`.
func (c *SheduleClient) Use(hooks ...Hook) {
	c.hooks.Shedule = append(c.hooks.Shedule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `shedule.Intercept(f(g(h())))`.
func (c *SheduleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Shedule = append(c.inters.Shedule, interceptors...)
}

// Create returns a builder for creating a Shedule entity.
func (c *SheduleClient) Create() *SheduleCreate {
	mutation := newSheduleMutation(c.config, OpCreate)
	return &SheduleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Shedule entities.
func (c *SheduleClient) CreateBulk(builders ...*SheduleCreate) *SheduleCreateBulk {
	return &SheduleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SheduleClient) MapCreateBulk(slice any, setFunc func(*SheduleCreate, int)) *SheduleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SheduleCreateBulk{err: fmt.Errorf("calling to SheduleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SheduleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SheduleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Shedule.
func (c *SheduleClient) Update() *SheduleUpdate {
	mutation := newSheduleMutation(c.config, OpUpdate)
	return &SheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SheduleClient) UpdateOne(_m *Shedule) *SheduleUpdateOne {
	mutation := newSheduleMutation(c.config, OpUpdateOne, withShedule(_m))
	return &SheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SheduleClient) UpdateOneID(id int) *SheduleUpdateOne {
	mutation := newSheduleMutation(c.config, OpUpdateOne, withSheduleID(id))
	return &SheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Shedule.
func (c *SheduleClient) Delete() *SheduleDelete {
	mutation := newSheduleMutation(c.config, OpDelete)
	return &SheduleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SheduleClient) DeleteOne(_m *Shedule) *SheduleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SheduleClient) DeleteOneID(id int) *SheduleDeleteOne {
	builder := c.Delete().Where(shedule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SheduleDeleteOne{builder}
}

// Query returns a query builder for Shedule.
func (c *SheduleClient) Query() *SheduleQuery {
	return &SheduleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeShedule},
		inters: c.Interceptors(),
	}
}

// Get returns a Shedule entity by its id.
func (c *SheduleClient) Get(ctx context.Context, id int) (*Shedule, error) {
	return c.Query().Where(shedule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SheduleClient) GetX(ctx context.Context, id int) *Shedule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SheduleClient) Hooks() []Hook {
	return c.hooks.Shedule
}

// Interceptors returns the client interceptors.
func (c *SheduleClient) Interceptors() []Interceptor {
	return c.inters.Shedule
}

func (c *SheduleClient) mutate(ctx context.Context, m *SheduleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SheduleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SheduleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SheduleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SheduleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Shedule mutation op: %q", m.Op())
	}
}

// TransportClient is a client for the Transport schema.
type TransportClient struct {
	config
}

// NewTransportClient returns a client for the Transport from the given config.
func NewTransportClient(c config) *TransportClient {
	return &TransportClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `transport.Hooks(f(g(h())))`.
func (c *TransportClient) Use(hooks ...Hook) {
	c.hooks.Transport = append(c.hooks.Transport, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `transport.Intercept(f(g(h())))`.
func (c *TransportClient) Intercept(interceptors ...Interceptor) {
	c.inters.Transport = append(c.inters.Transport, interceptors...)
}

// Create returns a builder for creating a Transport entity.
func (c *TransportClient) Create() *TransportCreate {
	mutation := newTransportMutation(c.config, OpCreate)
	return &TransportCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Transport entities.
func (c *TransportClient) CreateBulk(builders ...*TransportCreate) *TransportCreateBulk {
	return &TransportCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TransportClient) MapCreateBulk(slice any, setFunc func(*TransportCreate, int)) *TransportCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TransportCreateBulk{err: fmt.Errorf("calling to TransportClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TransportCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TransportCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Transport.
func (c *TransportClient) Update() *TransportUpdate {
	mutation := newTransportMutation(c.config, OpUpdate)
	return &TransportUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TransportClient) UpdateOne(_m *Transport) *TransportUpdateOne {
	mutation := newTransportMutation(c.config, OpUpdateOne, withTransport(_m))
	return &TransportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TransportClient) UpdateOneID(id int) *TransportUpdateOne {
	mutation := newTransportMutation(c.config, OpUpdateOne, withTransportID(id))
	return &TransportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Transport.
func (c *TransportClient) Delete() *TransportDelete {
	mutation := newTransportMutation(c.config, OpDelete)
	return &TransportDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TransportClient) DeleteOne(_m *Transport) *TransportDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TransportClient) DeleteOneID(id int) *TransportDeleteOne {
	builder := c.Delete().Where(transport.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TransportDeleteOne{builder}
}

// Query returns a query builder for Transport.
func (c *TransportClient) Query() *TransportQuery {
	return &TransportQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTransport},
		inters: c.Interceptors(),
	}
}

// Get returns a Transport entity by its id.
func (c *TransportClient) Get(ctx context.Context, id int) (*Transport, error) {
	return c.Query().Where(transport.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TransportClient) GetX(ctx context.Context, id int) *Transport {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TransportClient) Hooks() []Hook {
	return c.hooks.Transport
}

// Interceptors returns the client interceptors.
func (c *TransportClient) Interceptors() []Interceptor {
	return c.inters.Transport
}

func (c *TransportClient) mutate(ctx context.Context, m *TransportMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TransportCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TransportUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TransportUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TransportDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Transport mutation op: %q", m.Op())
	}
}

// TripClient is a client for the Trip schema.
type TripClient struct {
	config
}

// NewTripClient returns a client for the Trip from the given config.
func NewTripClient(c config) *TripClient {
	return &TripClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `trip.Hooks(f(g(h())))`.
func (c *TripClient) Use(hooks ...Hook) {
	c.hooks.Trip = append(c.hooks.Trip, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `trip.Intercept(f(g(h())))`.
func (c *TripClient) Intercept(interceptors ...Interceptor) {
	c.inters.Trip = append(c.inters.Trip, interceptors...)
}

// Create returns a builder for creating a Trip entity.
func (c *TripClient) Create() *TripCreate {
	mutation := newTripMutation(c.config, OpCreate)
	return &TripCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Trip entities.
func (c *TripClient) CreateBulk(builders ...*TripCreate) *TripCreateBulk {
	return &TripCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TripClient) MapCreateBulk(slice any, setFunc func(*TripCreate, int)) *TripCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TripCreateBulk{err: fmt.Errorf("calling to TripClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TripCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TripCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Trip.
func (c *TripClient) Update() *TripUpdate {
	mutation := newTripMutation(c.config, OpUpdate)
	return &TripUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TripClient) UpdateOne(_m *Trip) *TripUpdateOne {
	mutation := newTripMutation(c.config, OpUpdateOne, withTrip(_m))
	return &TripUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TripClient) UpdateOneID(id int) *TripUpdateOne {
	mutation := newTripMutation(c.config, OpUpdateOne, withTripID(id))
	return &TripUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Trip.
func (c *TripClient) Delete() *TripDelete {
	mutation := newTripMutation(c.config, OpDelete)
	return &TripDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TripClient) DeleteOne(_m *Trip) *TripDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TripClient) DeleteOneID(id int) *TripDeleteOne {
	builder := c.Delete().Where(trip.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TripDeleteOne{builder}
}

// Query returns a query builder for Trip.
func (c *TripClient) Query() *TripQuery {
	return &TripQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTrip},
		inters: c.Interceptors(),
	}
}

// Get returns a Trip entity by its id.
func (c *TripClient) Get(ctx context.Context, id int) (*Trip, error) {
	return c.Query().Where(trip.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TripClient) GetX(ctx context.Context, id int) *Trip {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TripClient) Hooks() []Hook {
	return c.hooks.Trip
}

// Interceptors returns the client interceptors.
func (c *TripClient) Interceptors() []Interceptor {
	return c.inters.Trip
}

func (c *TripClient) mutate(ctx context.Context, m *TripMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TripCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TripUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TripUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TripDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Trip mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a User.
func (c *UserClient) QueryOwner(_m *User) *PasswordTokenQuery {
	query := (&PasswordTokenClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(passwordtoken.Table, passwordtoken.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.OwnerTable, user.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Cost, Customer, GLog, GOrder, Guide, OrderNumber, PasswordToken, Shedule,
		Transport, Trip, User []ent.Hook
	}
	inters struct {
		Cost, Customer, GLog, GOrder, Guide, OrderNumber, PasswordToken, Shedule,
		Transport, Trip, User []ent.Interceptor
	}
)
