// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/customer"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
}

// SetFirstname sets the "firstname" field.
func (_c *CustomerCreate) SetFirstname(v string) *CustomerCreate {
	_c.mutation.SetFirstname(v)
	return _c
}

// SetLastname sets the "lastname" field.
func (_c *CustomerCreate) SetLastname(v string) *CustomerCreate {
	_c.mutation.SetLastname(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *CustomerCreate) SetPhone(v string) *CustomerCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *CustomerCreate) SetComment(v string) *CustomerCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *CustomerCreate) SetActive(v bool) *CustomerCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableActive(v *bool) *CustomerCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *CustomerCreate) SetEmail(v string) *CustomerCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *CustomerCreate) SetPassword(v string) *CustomerCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *CustomerCreate) SetCreated(v time.Time) *CustomerCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreated(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *CustomerCreate) SetUpdated(v time.Time) *CustomerCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableUpdated(v *time.Time) *CustomerCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CustomerCreate) SetCreatedBy(v int) *CustomerCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *CustomerCreate) SetNillableCreatedBy(v *int) *CustomerCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// Mutation returns the CustomerMutation object of the builder.
func (_c *CustomerCreate) Mutation() *CustomerMutation {
	return _c.mutation
}

// Save creates the Customer in the database.
func (_c *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomerCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := customer.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := customer.DefaultCreated
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := customer.DefaultUpdated
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := customer.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomerCreate) check() error {
	if _, ok := _c.mutation.Firstname(); !ok {
		return &ValidationError{Name: "firstname", err: errors.New(`ent: missing required field "Customer.firstname"`)}
	}
	if v, ok := _c.mutation.Firstname(); ok {
		if err := customer.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "Customer.firstname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Lastname(); !ok {
		return &ValidationError{Name: "lastname", err: errors.New(`ent: missing required field "Customer.lastname"`)}
	}
	if v, ok := _c.mutation.Lastname(); ok {
		if err := customer.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "Customer.lastname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Customer.phone"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "Customer.comment"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Customer.active"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Customer.email"`)}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Customer.password"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Customer.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Customer.updated"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Customer.created_by"`)}
	}
	return nil
}

func (_c *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Firstname(); ok {
		_spec.SetField(customer.FieldFirstname, field.TypeString, value)
		_node.Firstname = value
	}
	if value, ok := _c.mutation.Lastname(); ok {
		_spec.SetField(customer.FieldLastname, field.TypeString, value)
		_node.Lastname = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(customer.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(customer.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(customer.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(customer.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(customer.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(customer.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(customer.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(customer.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
}

// Save creates the Customer entities in the database.
func (_c *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Customer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
