// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/gcost"
)

// GCostCreate is the builder for creating a GCost entity.
type GCostCreate struct {
	config
	mutation *GCostMutation
	hooks    []Hook
}

// SetCost sets the "cost" field.
func (_c *GCostCreate) SetCost(v int) *GCostCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *GCostCreate) SetNillableCost(v *int) *GCostCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetTripID sets the "trip_id" field.
func (_c *GCostCreate) SetTripID(v int) *GCostCreate {
	_c.mutation.SetTripID(v)
	return _c
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_c *GCostCreate) SetNillableTripID(v *int) *GCostCreate {
	if v != nil {
		_c.SetTripID(*v)
	}
	return _c
}

// SetTransportID sets the "transport_id" field.
func (_c *GCostCreate) SetTransportID(v int) *GCostCreate {
	_c.mutation.SetTransportID(v)
	return _c
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_c *GCostCreate) SetNillableTransportID(v *int) *GCostCreate {
	if v != nil {
		_c.SetTransportID(*v)
	}
	return _c
}

// Mutation returns the GCostMutation object of the builder.
func (_c *GCostCreate) Mutation() *GCostMutation {
	return _c.mutation
}

// Save creates the GCost in the database.
func (_c *GCostCreate) Save(ctx context.Context) (*GCost, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GCostCreate) SaveX(ctx context.Context) *GCost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GCostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GCostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GCostCreate) defaults() {
	if _, ok := _c.mutation.Cost(); !ok {
		v := gcost.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.TripID(); !ok {
		v := gcost.DefaultTripID
		_c.mutation.SetTripID(v)
	}
	if _, ok := _c.mutation.TransportID(); !ok {
		v := gcost.DefaultTransportID
		_c.mutation.SetTransportID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GCostCreate) check() error {
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "GCost.cost"`)}
	}
	if _, ok := _c.mutation.TripID(); !ok {
		return &ValidationError{Name: "trip_id", err: errors.New(`ent: missing required field "GCost.trip_id"`)}
	}
	if _, ok := _c.mutation.TransportID(); !ok {
		return &ValidationError{Name: "transport_id", err: errors.New(`ent: missing required field "GCost.transport_id"`)}
	}
	return nil
}

func (_c *GCostCreate) sqlSave(ctx context.Context) (*GCost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GCostCreate) createSpec() (*GCost, *sqlgraph.CreateSpec) {
	var (
		_node = &GCost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gcost.Table, sqlgraph.NewFieldSpec(gcost.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(gcost.FieldCost, field.TypeInt, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.TripID(); ok {
		_spec.SetField(gcost.FieldTripID, field.TypeInt, value)
		_node.TripID = value
	}
	if value, ok := _c.mutation.TransportID(); ok {
		_spec.SetField(gcost.FieldTransportID, field.TypeInt, value)
		_node.TransportID = value
	}
	return _node, _spec
}

// GCostCreateBulk is the builder for creating many GCost entities in bulk.
type GCostCreateBulk struct {
	config
	err      error
	builders []*GCostCreate
}

// Save creates the GCost entities in the database.
func (_c *GCostCreateBulk) Save(ctx context.Context) ([]*GCost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GCost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GCostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GCostCreateBulk) SaveX(ctx context.Context) []*GCost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GCostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GCostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
