// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/gcost"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// GCostUpdate is the builder for updating GCost entities.
type GCostUpdate struct {
	config
	hooks    []Hook
	mutation *GCostMutation
}

// Where appends a list predicates to the GCostUpdate builder.
func (_u *GCostUpdate) Where(ps ...predicate.GCost) *GCostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCost sets the "cost" field.
func (_u *GCostUpdate) SetCost(v int) *GCostUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *GCostUpdate) SetNillableCost(v *int) *GCostUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *GCostUpdate) AddCost(v int) *GCostUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *GCostUpdate) SetTripID(v int) *GCostUpdate {
	_u.mutation.ResetTripID()
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *GCostUpdate) SetNillableTripID(v *int) *GCostUpdate {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// AddTripID adds value to the "trip_id" field.
func (_u *GCostUpdate) AddTripID(v int) *GCostUpdate {
	_u.mutation.AddTripID(v)
	return _u
}

// SetTransportID sets the "transport_id" field.
func (_u *GCostUpdate) SetTransportID(v int) *GCostUpdate {
	_u.mutation.ResetTransportID()
	_u.mutation.SetTransportID(v)
	return _u
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_u *GCostUpdate) SetNillableTransportID(v *int) *GCostUpdate {
	if v != nil {
		_u.SetTransportID(*v)
	}
	return _u
}

// AddTransportID adds value to the "transport_id" field.
func (_u *GCostUpdate) AddTransportID(v int) *GCostUpdate {
	_u.mutation.AddTransportID(v)
	return _u
}

// Mutation returns the GCostMutation object of the builder.
func (_u *GCostUpdate) Mutation() *GCostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GCostUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GCostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GCostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GCostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GCostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gcost.Table, gcost.Columns, sqlgraph.NewFieldSpec(gcost.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(gcost.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(gcost.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TripID(); ok {
		_spec.SetField(gcost.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTripID(); ok {
		_spec.AddField(gcost.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TransportID(); ok {
		_spec.SetField(gcost.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTransportID(); ok {
		_spec.AddField(gcost.FieldTransportID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gcost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GCostUpdateOne is the builder for updating a single GCost entity.
type GCostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GCostMutation
}

// SetCost sets the "cost" field.
func (_u *GCostUpdateOne) SetCost(v int) *GCostUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *GCostUpdateOne) SetNillableCost(v *int) *GCostUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *GCostUpdateOne) AddCost(v int) *GCostUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *GCostUpdateOne) SetTripID(v int) *GCostUpdateOne {
	_u.mutation.ResetTripID()
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *GCostUpdateOne) SetNillableTripID(v *int) *GCostUpdateOne {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// AddTripID adds value to the "trip_id" field.
func (_u *GCostUpdateOne) AddTripID(v int) *GCostUpdateOne {
	_u.mutation.AddTripID(v)
	return _u
}

// SetTransportID sets the "transport_id" field.
func (_u *GCostUpdateOne) SetTransportID(v int) *GCostUpdateOne {
	_u.mutation.ResetTransportID()
	_u.mutation.SetTransportID(v)
	return _u
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_u *GCostUpdateOne) SetNillableTransportID(v *int) *GCostUpdateOne {
	if v != nil {
		_u.SetTransportID(*v)
	}
	return _u
}

// AddTransportID adds value to the "transport_id" field.
func (_u *GCostUpdateOne) AddTransportID(v int) *GCostUpdateOne {
	_u.mutation.AddTransportID(v)
	return _u
}

// Mutation returns the GCostMutation object of the builder.
func (_u *GCostUpdateOne) Mutation() *GCostMutation {
	return _u.mutation
}

// Where appends a list predicates to the GCostUpdate builder.
func (_u *GCostUpdateOne) Where(ps ...predicate.GCost) *GCostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GCostUpdateOne) Select(field string, fields ...string) *GCostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GCost entity.
func (_u *GCostUpdateOne) Save(ctx context.Context) (*GCost, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GCostUpdateOne) SaveX(ctx context.Context) *GCost {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GCostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GCostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GCostUpdateOne) sqlSave(ctx context.Context) (_node *GCost, err error) {
	_spec := sqlgraph.NewUpdateSpec(gcost.Table, gcost.Columns, sqlgraph.NewFieldSpec(gcost.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GCost.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gcost.FieldID)
		for _, f := range fields {
			if !gcost.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gcost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(gcost.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(gcost.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TripID(); ok {
		_spec.SetField(gcost.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTripID(); ok {
		_spec.AddField(gcost.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TransportID(); ok {
		_spec.SetField(gcost.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTransportID(); ok {
		_spec.AddField(gcost.FieldTransportID, field.TypeInt, value)
	}
	_node = &GCost{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gcost.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
