// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/glog"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// GLogUpdate is the builder for updating GLog entities.
type GLogUpdate struct {
	config
	hooks    []Hook
	mutation *GLogMutation
}

// Where appends a list predicates to the GLogUpdate builder.
func (_u *GLogUpdate) Where(ps ...predicate.GLog) *GLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *GLogUpdate) SetAction(v string) *GLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *GLogUpdate) SetNillableAction(v *string) *GLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GLogUpdate) SetComment(v string) *GLogUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GLogUpdate) SetNillableComment(v *string) *GLogUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GLogUpdate) SetCreatedBy(v int) *GLogUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GLogUpdate) SetNillableCreatedBy(v *int) *GLogUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GLogUpdate) AddCreatedBy(v int) *GLogUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the GLogMutation object of the builder.
func (_u *GLogUpdate) Mutation() *GLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := glog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "GLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *GLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(glog.Table, glog.Columns, sqlgraph.NewFieldSpec(glog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(glog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(glog.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(glog.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(glog.FieldCreatedBy, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{glog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GLogUpdateOne is the builder for updating a single GLog entity.
type GLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GLogMutation
}

// SetAction sets the "action" field.
func (_u *GLogUpdateOne) SetAction(v string) *GLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *GLogUpdateOne) SetNillableAction(v *string) *GLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GLogUpdateOne) SetComment(v string) *GLogUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GLogUpdateOne) SetNillableComment(v *string) *GLogUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GLogUpdateOne) SetCreatedBy(v int) *GLogUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GLogUpdateOne) SetNillableCreatedBy(v *int) *GLogUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GLogUpdateOne) AddCreatedBy(v int) *GLogUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the GLogMutation object of the builder.
func (_u *GLogUpdateOne) Mutation() *GLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the GLogUpdate builder.
func (_u *GLogUpdateOne) Where(ps ...predicate.GLog) *GLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GLogUpdateOne) Select(field string, fields ...string) *GLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GLog entity.
func (_u *GLogUpdateOne) Save(ctx context.Context) (*GLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GLogUpdateOne) SaveX(ctx context.Context) *GLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := glog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "GLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *GLogUpdateOne) sqlSave(ctx context.Context) (_node *GLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(glog.Table, glog.Columns, sqlgraph.NewFieldSpec(glog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, glog.FieldID)
		for _, f := range fields {
			if !glog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != glog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(glog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(glog.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(glog.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(glog.FieldCreatedBy, field.TypeInt, value)
	}
	_node = &GLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{glog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
