// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/gorder"
)

// GOrderCreate is the builder for creating a GOrder entity.
type GOrderCreate struct {
	config
	mutation *GOrderMutation
	hooks    []Hook
}

// SetNum sets the "num" field.
func (_c *GOrderCreate) SetNum(v int) *GOrderCreate {
	_c.mutation.SetNum(v)
	return _c
}

// SetNillableNum sets the "num" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableNum(v *int) *GOrderCreate {
	if v != nil {
		_c.SetNum(*v)
	}
	return _c
}

// SetTripID sets the "trip_id" field.
func (_c *GOrderCreate) SetTripID(v int) *GOrderCreate {
	_c.mutation.SetTripID(v)
	return _c
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableTripID(v *int) *GOrderCreate {
	if v != nil {
		_c.SetTripID(*v)
	}
	return _c
}

// SetCountPerson sets the "count_person" field.
func (_c *GOrderCreate) SetCountPerson(v int) *GOrderCreate {
	_c.mutation.SetCountPerson(v)
	return _c
}

// SetNillableCountPerson sets the "count_person" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableCountPerson(v *int) *GOrderCreate {
	if v != nil {
		_c.SetCountPerson(*v)
	}
	return _c
}

// SetDay sets the "day" field.
func (_c *GOrderCreate) SetDay(v time.Time) *GOrderCreate {
	_c.mutation.SetDay(v)
	return _c
}

// SetBegin sets the "begin" field.
func (_c *GOrderCreate) SetBegin(v time.Time) *GOrderCreate {
	_c.mutation.SetBegin(v)
	return _c
}

// SetTransportID sets the "transport_id" field.
func (_c *GOrderCreate) SetTransportID(v int) *GOrderCreate {
	_c.mutation.SetTransportID(v)
	return _c
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableTransportID(v *int) *GOrderCreate {
	if v != nil {
		_c.SetTransportID(*v)
	}
	return _c
}

// SetGuideID sets the "guide_id" field.
func (_c *GOrderCreate) SetGuideID(v int) *GOrderCreate {
	_c.mutation.SetGuideID(v)
	return _c
}

// SetNillableGuideID sets the "guide_id" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableGuideID(v *int) *GOrderCreate {
	if v != nil {
		_c.SetGuideID(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *GOrderCreate) SetCost(v int) *GOrderCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableCost(v *int) *GOrderCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GOrderCreate) SetStatus(v int) *GOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableStatus(v *int) *GOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPayStatus sets the "pay_status" field.
func (_c *GOrderCreate) SetPayStatus(v int) *GOrderCreate {
	_c.mutation.SetPayStatus(v)
	return _c
}

// SetNillablePayStatus sets the "pay_status" field if the given value is not nil.
func (_c *GOrderCreate) SetNillablePayStatus(v *int) *GOrderCreate {
	if v != nil {
		_c.SetPayStatus(*v)
	}
	return _c
}

// SetPaidSum sets the "paid_sum" field.
func (_c *GOrderCreate) SetPaidSum(v int) *GOrderCreate {
	_c.mutation.SetPaidSum(v)
	return _c
}

// SetNillablePaidSum sets the "paid_sum" field if the given value is not nil.
func (_c *GOrderCreate) SetNillablePaidSum(v *int) *GOrderCreate {
	if v != nil {
		_c.SetPaidSum(*v)
	}
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *GOrderCreate) SetCustomerID(v int) *GOrderCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableCustomerID(v *int) *GOrderCreate {
	if v != nil {
		_c.SetCustomerID(*v)
	}
	return _c
}

// SetPlace sets the "place" field.
func (_c *GOrderCreate) SetPlace(v string) *GOrderCreate {
	_c.mutation.SetPlace(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *GOrderCreate) SetComment(v string) *GOrderCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetCreated sets the "created" field.
func (_c *GOrderCreate) SetCreated(v time.Time) *GOrderCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableCreated(v *time.Time) *GOrderCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *GOrderCreate) SetUpdated(v time.Time) *GOrderCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableUpdated(v *time.Time) *GOrderCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GOrderCreate) SetCreatedBy(v int) *GOrderCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableCreatedBy(v *int) *GOrderCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetArchived sets the "archived" field.
func (_c *GOrderCreate) SetArchived(v bool) *GOrderCreate {
	_c.mutation.SetArchived(v)
	return _c
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_c *GOrderCreate) SetNillableArchived(v *bool) *GOrderCreate {
	if v != nil {
		_c.SetArchived(*v)
	}
	return _c
}

// Mutation returns the GOrderMutation object of the builder.
func (_c *GOrderCreate) Mutation() *GOrderMutation {
	return _c.mutation
}

// Save creates the GOrder in the database.
func (_c *GOrderCreate) Save(ctx context.Context) (*GOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GOrderCreate) SaveX(ctx context.Context) *GOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GOrderCreate) defaults() {
	if _, ok := _c.mutation.Num(); !ok {
		v := gorder.DefaultNum
		_c.mutation.SetNum(v)
	}
	if _, ok := _c.mutation.TripID(); !ok {
		v := gorder.DefaultTripID
		_c.mutation.SetTripID(v)
	}
	if _, ok := _c.mutation.CountPerson(); !ok {
		v := gorder.DefaultCountPerson
		_c.mutation.SetCountPerson(v)
	}
	if _, ok := _c.mutation.TransportID(); !ok {
		v := gorder.DefaultTransportID
		_c.mutation.SetTransportID(v)
	}
	if _, ok := _c.mutation.GuideID(); !ok {
		v := gorder.DefaultGuideID
		_c.mutation.SetGuideID(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := gorder.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := gorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PayStatus(); !ok {
		v := gorder.DefaultPayStatus
		_c.mutation.SetPayStatus(v)
	}
	if _, ok := _c.mutation.PaidSum(); !ok {
		v := gorder.DefaultPaidSum
		_c.mutation.SetPaidSum(v)
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		v := gorder.DefaultCustomerID
		_c.mutation.SetCustomerID(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := gorder.DefaultCreated
		_c.mutation.SetCreated(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := gorder.DefaultUpdated
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := gorder.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.Archived(); !ok {
		v := gorder.DefaultArchived
		_c.mutation.SetArchived(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GOrderCreate) check() error {
	if _, ok := _c.mutation.Num(); !ok {
		return &ValidationError{Name: "num", err: errors.New(`ent: missing required field "GOrder.num"`)}
	}
	if _, ok := _c.mutation.TripID(); !ok {
		return &ValidationError{Name: "trip_id", err: errors.New(`ent: missing required field "GOrder.trip_id"`)}
	}
	if _, ok := _c.mutation.CountPerson(); !ok {
		return &ValidationError{Name: "count_person", err: errors.New(`ent: missing required field "GOrder.count_person"`)}
	}
	if _, ok := _c.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "GOrder.day"`)}
	}
	if _, ok := _c.mutation.Begin(); !ok {
		return &ValidationError{Name: "begin", err: errors.New(`ent: missing required field "GOrder.begin"`)}
	}
	if _, ok := _c.mutation.TransportID(); !ok {
		return &ValidationError{Name: "transport_id", err: errors.New(`ent: missing required field "GOrder.transport_id"`)}
	}
	if _, ok := _c.mutation.GuideID(); !ok {
		return &ValidationError{Name: "guide_id", err: errors.New(`ent: missing required field "GOrder.guide_id"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "GOrder.cost"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GOrder.status"`)}
	}
	if _, ok := _c.mutation.PayStatus(); !ok {
		return &ValidationError{Name: "pay_status", err: errors.New(`ent: missing required field "GOrder.pay_status"`)}
	}
	if _, ok := _c.mutation.PaidSum(); !ok {
		return &ValidationError{Name: "paid_sum", err: errors.New(`ent: missing required field "GOrder.paid_sum"`)}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "GOrder.customer_id"`)}
	}
	if _, ok := _c.mutation.Place(); !ok {
		return &ValidationError{Name: "place", err: errors.New(`ent: missing required field "GOrder.place"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "GOrder.comment"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "GOrder.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "GOrder.updated"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "GOrder.created_by"`)}
	}
	if _, ok := _c.mutation.Archived(); !ok {
		return &ValidationError{Name: "archived", err: errors.New(`ent: missing required field "GOrder.archived"`)}
	}
	return nil
}

func (_c *GOrderCreate) sqlSave(ctx context.Context) (*GOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GOrderCreate) createSpec() (*GOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &GOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gorder.Table, sqlgraph.NewFieldSpec(gorder.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Num(); ok {
		_spec.SetField(gorder.FieldNum, field.TypeInt, value)
		_node.Num = value
	}
	if value, ok := _c.mutation.TripID(); ok {
		_spec.SetField(gorder.FieldTripID, field.TypeInt, value)
		_node.TripID = value
	}
	if value, ok := _c.mutation.CountPerson(); ok {
		_spec.SetField(gorder.FieldCountPerson, field.TypeInt, value)
		_node.CountPerson = value
	}
	if value, ok := _c.mutation.Day(); ok {
		_spec.SetField(gorder.FieldDay, field.TypeTime, value)
		_node.Day = value
	}
	if value, ok := _c.mutation.Begin(); ok {
		_spec.SetField(gorder.FieldBegin, field.TypeTime, value)
		_node.Begin = value
	}
	if value, ok := _c.mutation.TransportID(); ok {
		_spec.SetField(gorder.FieldTransportID, field.TypeInt, value)
		_node.TransportID = value
	}
	if value, ok := _c.mutation.GuideID(); ok {
		_spec.SetField(gorder.FieldGuideID, field.TypeInt, value)
		_node.GuideID = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(gorder.FieldCost, field.TypeInt, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(gorder.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PayStatus(); ok {
		_spec.SetField(gorder.FieldPayStatus, field.TypeInt, value)
		_node.PayStatus = value
	}
	if value, ok := _c.mutation.PaidSum(); ok {
		_spec.SetField(gorder.FieldPaidSum, field.TypeInt, value)
		_node.PaidSum = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(gorder.FieldCustomerID, field.TypeInt, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.Place(); ok {
		_spec.SetField(gorder.FieldPlace, field.TypeString, value)
		_node.Place = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(gorder.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(gorder.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(gorder.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(gorder.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.Archived(); ok {
		_spec.SetField(gorder.FieldArchived, field.TypeBool, value)
		_node.Archived = value
	}
	return _node, _spec
}

// GOrderCreateBulk is the builder for creating many GOrder entities in bulk.
type GOrderCreateBulk struct {
	config
	err      error
	builders []*GOrderCreate
}

// Save creates the GOrder entities in the database.
func (_c *GOrderCreateBulk) Save(ctx context.Context) ([]*GOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GOrderCreateBulk) SaveX(ctx context.Context) []*GOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
