// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/gorder"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// GOrderUpdate is the builder for updating GOrder entities.
type GOrderUpdate struct {
	config
	hooks    []Hook
	mutation *GOrderMutation
}

// Where appends a list predicates to the GOrderUpdate builder.
func (_u *GOrderUpdate) Where(ps ...predicate.GOrder) *GOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNum sets the "num" field.
func (_u *GOrderUpdate) SetNum(v int) *GOrderUpdate {
	_u.mutation.ResetNum()
	_u.mutation.SetNum(v)
	return _u
}

// SetNillableNum sets the "num" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableNum(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetNum(*v)
	}
	return _u
}

// AddNum adds value to the "num" field.
func (_u *GOrderUpdate) AddNum(v int) *GOrderUpdate {
	_u.mutation.AddNum(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *GOrderUpdate) SetTripID(v int) *GOrderUpdate {
	_u.mutation.ResetTripID()
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableTripID(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// AddTripID adds value to the "trip_id" field.
func (_u *GOrderUpdate) AddTripID(v int) *GOrderUpdate {
	_u.mutation.AddTripID(v)
	return _u
}

// SetCountPerson sets the "count_person" field.
func (_u *GOrderUpdate) SetCountPerson(v int) *GOrderUpdate {
	_u.mutation.ResetCountPerson()
	_u.mutation.SetCountPerson(v)
	return _u
}

// SetNillableCountPerson sets the "count_person" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableCountPerson(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetCountPerson(*v)
	}
	return _u
}

// AddCountPerson adds value to the "count_person" field.
func (_u *GOrderUpdate) AddCountPerson(v int) *GOrderUpdate {
	_u.mutation.AddCountPerson(v)
	return _u
}

// SetDay sets the "day" field.
func (_u *GOrderUpdate) SetDay(v time.Time) *GOrderUpdate {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableDay(v *time.Time) *GOrderUpdate {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetBegin sets the "begin" field.
func (_u *GOrderUpdate) SetBegin(v time.Time) *GOrderUpdate {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableBegin(v *time.Time) *GOrderUpdate {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetTransportID sets the "transport_id" field.
func (_u *GOrderUpdate) SetTransportID(v int) *GOrderUpdate {
	_u.mutation.ResetTransportID()
	_u.mutation.SetTransportID(v)
	return _u
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableTransportID(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetTransportID(*v)
	}
	return _u
}

// AddTransportID adds value to the "transport_id" field.
func (_u *GOrderUpdate) AddTransportID(v int) *GOrderUpdate {
	_u.mutation.AddTransportID(v)
	return _u
}

// SetGuideID sets the "guide_id" field.
func (_u *GOrderUpdate) SetGuideID(v int) *GOrderUpdate {
	_u.mutation.ResetGuideID()
	_u.mutation.SetGuideID(v)
	return _u
}

// SetNillableGuideID sets the "guide_id" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableGuideID(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetGuideID(*v)
	}
	return _u
}

// AddGuideID adds value to the "guide_id" field.
func (_u *GOrderUpdate) AddGuideID(v int) *GOrderUpdate {
	_u.mutation.AddGuideID(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *GOrderUpdate) SetCost(v int) *GOrderUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableCost(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *GOrderUpdate) AddCost(v int) *GOrderUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GOrderUpdate) SetStatus(v int) *GOrderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableStatus(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GOrderUpdate) AddStatus(v int) *GOrderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPayStatus sets the "pay_status" field.
func (_u *GOrderUpdate) SetPayStatus(v int) *GOrderUpdate {
	_u.mutation.ResetPayStatus()
	_u.mutation.SetPayStatus(v)
	return _u
}

// SetNillablePayStatus sets the "pay_status" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillablePayStatus(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetPayStatus(*v)
	}
	return _u
}

// AddPayStatus adds value to the "pay_status" field.
func (_u *GOrderUpdate) AddPayStatus(v int) *GOrderUpdate {
	_u.mutation.AddPayStatus(v)
	return _u
}

// SetPaidSum sets the "paid_sum" field.
func (_u *GOrderUpdate) SetPaidSum(v int) *GOrderUpdate {
	_u.mutation.ResetPaidSum()
	_u.mutation.SetPaidSum(v)
	return _u
}

// SetNillablePaidSum sets the "paid_sum" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillablePaidSum(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetPaidSum(*v)
	}
	return _u
}

// AddPaidSum adds value to the "paid_sum" field.
func (_u *GOrderUpdate) AddPaidSum(v int) *GOrderUpdate {
	_u.mutation.AddPaidSum(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *GOrderUpdate) SetCustomerID(v int) *GOrderUpdate {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableCustomerID(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *GOrderUpdate) AddCustomerID(v int) *GOrderUpdate {
	_u.mutation.AddCustomerID(v)
	return _u
}

// SetPlace sets the "place" field.
func (_u *GOrderUpdate) SetPlace(v string) *GOrderUpdate {
	_u.mutation.SetPlace(v)
	return _u
}

// SetNillablePlace sets the "place" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillablePlace(v *string) *GOrderUpdate {
	if v != nil {
		_u.SetPlace(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GOrderUpdate) SetComment(v string) *GOrderUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableComment(v *string) *GOrderUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GOrderUpdate) SetUpdated(v time.Time) *GOrderUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableUpdated(v *time.Time) *GOrderUpdate {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GOrderUpdate) SetCreatedBy(v int) *GOrderUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableCreatedBy(v *int) *GOrderUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GOrderUpdate) AddCreatedBy(v int) *GOrderUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetArchived sets the "archived" field.
func (_u *GOrderUpdate) SetArchived(v bool) *GOrderUpdate {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *GOrderUpdate) SetNillableArchived(v *bool) *GOrderUpdate {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// Mutation returns the GOrderMutation object of the builder.
func (_u *GOrderUpdate) Mutation() *GOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gorder.Table, gorder.Columns, sqlgraph.NewFieldSpec(gorder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Num(); ok {
		_spec.SetField(gorder.FieldNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNum(); ok {
		_spec.AddField(gorder.FieldNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TripID(); ok {
		_spec.SetField(gorder.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTripID(); ok {
		_spec.AddField(gorder.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CountPerson(); ok {
		_spec.SetField(gorder.FieldCountPerson, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCountPerson(); ok {
		_spec.AddField(gorder.FieldCountPerson, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(gorder.FieldDay, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(gorder.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TransportID(); ok {
		_spec.SetField(gorder.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTransportID(); ok {
		_spec.AddField(gorder.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GuideID(); ok {
		_spec.SetField(gorder.FieldGuideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGuideID(); ok {
		_spec.AddField(gorder.FieldGuideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(gorder.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(gorder.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gorder.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gorder.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayStatus(); ok {
		_spec.SetField(gorder.FieldPayStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayStatus(); ok {
		_spec.AddField(gorder.FieldPayStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PaidSum(); ok {
		_spec.SetField(gorder.FieldPaidSum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaidSum(); ok {
		_spec.AddField(gorder.FieldPaidSum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(gorder.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(gorder.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Place(); ok {
		_spec.SetField(gorder.FieldPlace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(gorder.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(gorder.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(gorder.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(gorder.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(gorder.FieldArchived, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GOrderUpdateOne is the builder for updating a single GOrder entity.
type GOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GOrderMutation
}

// SetNum sets the "num" field.
func (_u *GOrderUpdateOne) SetNum(v int) *GOrderUpdateOne {
	_u.mutation.ResetNum()
	_u.mutation.SetNum(v)
	return _u
}

// SetNillableNum sets the "num" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableNum(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetNum(*v)
	}
	return _u
}

// AddNum adds value to the "num" field.
func (_u *GOrderUpdateOne) AddNum(v int) *GOrderUpdateOne {
	_u.mutation.AddNum(v)
	return _u
}

// SetTripID sets the "trip_id" field.
func (_u *GOrderUpdateOne) SetTripID(v int) *GOrderUpdateOne {
	_u.mutation.ResetTripID()
	_u.mutation.SetTripID(v)
	return _u
}

// SetNillableTripID sets the "trip_id" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableTripID(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetTripID(*v)
	}
	return _u
}

// AddTripID adds value to the "trip_id" field.
func (_u *GOrderUpdateOne) AddTripID(v int) *GOrderUpdateOne {
	_u.mutation.AddTripID(v)
	return _u
}

// SetCountPerson sets the "count_person" field.
func (_u *GOrderUpdateOne) SetCountPerson(v int) *GOrderUpdateOne {
	_u.mutation.ResetCountPerson()
	_u.mutation.SetCountPerson(v)
	return _u
}

// SetNillableCountPerson sets the "count_person" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableCountPerson(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetCountPerson(*v)
	}
	return _u
}

// AddCountPerson adds value to the "count_person" field.
func (_u *GOrderUpdateOne) AddCountPerson(v int) *GOrderUpdateOne {
	_u.mutation.AddCountPerson(v)
	return _u
}

// SetDay sets the "day" field.
func (_u *GOrderUpdateOne) SetDay(v time.Time) *GOrderUpdateOne {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableDay(v *time.Time) *GOrderUpdateOne {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetBegin sets the "begin" field.
func (_u *GOrderUpdateOne) SetBegin(v time.Time) *GOrderUpdateOne {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableBegin(v *time.Time) *GOrderUpdateOne {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetTransportID sets the "transport_id" field.
func (_u *GOrderUpdateOne) SetTransportID(v int) *GOrderUpdateOne {
	_u.mutation.ResetTransportID()
	_u.mutation.SetTransportID(v)
	return _u
}

// SetNillableTransportID sets the "transport_id" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableTransportID(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetTransportID(*v)
	}
	return _u
}

// AddTransportID adds value to the "transport_id" field.
func (_u *GOrderUpdateOne) AddTransportID(v int) *GOrderUpdateOne {
	_u.mutation.AddTransportID(v)
	return _u
}

// SetGuideID sets the "guide_id" field.
func (_u *GOrderUpdateOne) SetGuideID(v int) *GOrderUpdateOne {
	_u.mutation.ResetGuideID()
	_u.mutation.SetGuideID(v)
	return _u
}

// SetNillableGuideID sets the "guide_id" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableGuideID(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetGuideID(*v)
	}
	return _u
}

// AddGuideID adds value to the "guide_id" field.
func (_u *GOrderUpdateOne) AddGuideID(v int) *GOrderUpdateOne {
	_u.mutation.AddGuideID(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *GOrderUpdateOne) SetCost(v int) *GOrderUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableCost(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *GOrderUpdateOne) AddCost(v int) *GOrderUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GOrderUpdateOne) SetStatus(v int) *GOrderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableStatus(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GOrderUpdateOne) AddStatus(v int) *GOrderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPayStatus sets the "pay_status" field.
func (_u *GOrderUpdateOne) SetPayStatus(v int) *GOrderUpdateOne {
	_u.mutation.ResetPayStatus()
	_u.mutation.SetPayStatus(v)
	return _u
}

// SetNillablePayStatus sets the "pay_status" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillablePayStatus(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetPayStatus(*v)
	}
	return _u
}

// AddPayStatus adds value to the "pay_status" field.
func (_u *GOrderUpdateOne) AddPayStatus(v int) *GOrderUpdateOne {
	_u.mutation.AddPayStatus(v)
	return _u
}

// SetPaidSum sets the "paid_sum" field.
func (_u *GOrderUpdateOne) SetPaidSum(v int) *GOrderUpdateOne {
	_u.mutation.ResetPaidSum()
	_u.mutation.SetPaidSum(v)
	return _u
}

// SetNillablePaidSum sets the "paid_sum" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillablePaidSum(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetPaidSum(*v)
	}
	return _u
}

// AddPaidSum adds value to the "paid_sum" field.
func (_u *GOrderUpdateOne) AddPaidSum(v int) *GOrderUpdateOne {
	_u.mutation.AddPaidSum(v)
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *GOrderUpdateOne) SetCustomerID(v int) *GOrderUpdateOne {
	_u.mutation.ResetCustomerID()
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableCustomerID(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// AddCustomerID adds value to the "customer_id" field.
func (_u *GOrderUpdateOne) AddCustomerID(v int) *GOrderUpdateOne {
	_u.mutation.AddCustomerID(v)
	return _u
}

// SetPlace sets the "place" field.
func (_u *GOrderUpdateOne) SetPlace(v string) *GOrderUpdateOne {
	_u.mutation.SetPlace(v)
	return _u
}

// SetNillablePlace sets the "place" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillablePlace(v *string) *GOrderUpdateOne {
	if v != nil {
		_u.SetPlace(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GOrderUpdateOne) SetComment(v string) *GOrderUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableComment(v *string) *GOrderUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *GOrderUpdateOne) SetUpdated(v time.Time) *GOrderUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableUpdated(v *time.Time) *GOrderUpdateOne {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GOrderUpdateOne) SetCreatedBy(v int) *GOrderUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableCreatedBy(v *int) *GOrderUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GOrderUpdateOne) AddCreatedBy(v int) *GOrderUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetArchived sets the "archived" field.
func (_u *GOrderUpdateOne) SetArchived(v bool) *GOrderUpdateOne {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *GOrderUpdateOne) SetNillableArchived(v *bool) *GOrderUpdateOne {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// Mutation returns the GOrderMutation object of the builder.
func (_u *GOrderUpdateOne) Mutation() *GOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the GOrderUpdate builder.
func (_u *GOrderUpdateOne) Where(ps ...predicate.GOrder) *GOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GOrderUpdateOne) Select(field string, fields ...string) *GOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GOrder entity.
func (_u *GOrderUpdateOne) Save(ctx context.Context) (*GOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GOrderUpdateOne) SaveX(ctx context.Context) *GOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GOrderUpdateOne) sqlSave(ctx context.Context) (_node *GOrder, err error) {
	_spec := sqlgraph.NewUpdateSpec(gorder.Table, gorder.Columns, sqlgraph.NewFieldSpec(gorder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gorder.FieldID)
		for _, f := range fields {
			if !gorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Num(); ok {
		_spec.SetField(gorder.FieldNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNum(); ok {
		_spec.AddField(gorder.FieldNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TripID(); ok {
		_spec.SetField(gorder.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTripID(); ok {
		_spec.AddField(gorder.FieldTripID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CountPerson(); ok {
		_spec.SetField(gorder.FieldCountPerson, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCountPerson(); ok {
		_spec.AddField(gorder.FieldCountPerson, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(gorder.FieldDay, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(gorder.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TransportID(); ok {
		_spec.SetField(gorder.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTransportID(); ok {
		_spec.AddField(gorder.FieldTransportID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GuideID(); ok {
		_spec.SetField(gorder.FieldGuideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGuideID(); ok {
		_spec.AddField(gorder.FieldGuideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(gorder.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(gorder.FieldCost, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gorder.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(gorder.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PayStatus(); ok {
		_spec.SetField(gorder.FieldPayStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayStatus(); ok {
		_spec.AddField(gorder.FieldPayStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PaidSum(); ok {
		_spec.SetField(gorder.FieldPaidSum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaidSum(); ok {
		_spec.AddField(gorder.FieldPaidSum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomerID(); ok {
		_spec.SetField(gorder.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCustomerID(); ok {
		_spec.AddField(gorder.FieldCustomerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Place(); ok {
		_spec.SetField(gorder.FieldPlace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(gorder.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(gorder.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(gorder.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(gorder.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(gorder.FieldArchived, field.TypeBool, value)
	}
	_node = &GOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
