// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/gorder"
)

// GOrder is the model entity for the GOrder schema.
type GOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Num holds the value of the "num" field.
	Num int `json:"num,omitempty"`
	// TripID holds the value of the "trip_id" field.
	TripID int `json:"trip_id,omitempty"`
	// TouristCount holds the value of the "tourist_count" field.
	TouristCount int `json:"tourist_count,omitempty"`
	// Day holds the value of the "day" field.
	Day time.Time `json:"day,omitempty"`
	// Begin holds the value of the "begin" field.
	Begin time.Time `json:"begin,omitempty"`
	// TransportID holds the value of the "transport_id" field.
	TransportID int `json:"transport_id,omitempty"`
	// GuideID holds the value of the "guide_id" field.
	GuideID int `json:"guide_id,omitempty"`
	// Cost holds the value of the "cost" field.
	Cost int `json:"cost,omitempty"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitempty"`
	// PayStatus holds the value of the "pay_status" field.
	PayStatus int `json:"pay_status,omitempty"`
	// PaidSum holds the value of the "paid_sum" field.
	PaidSum int `json:"paid_sum,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID int `json:"customer_id,omitempty"`
	// Place holds the value of the "place" field.
	Place string `json:"place,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
	// Created holds the value of the "created" field.
	Created time.Time `json:"created,omitempty"`
	// Updated holds the value of the "updated" field.
	Updated time.Time `json:"updated,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// Archived holds the value of the "archived" field.
	Archived     bool `json:"archived,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gorder.FieldArchived:
			values[i] = new(sql.NullBool)
		case gorder.FieldID, gorder.FieldNum, gorder.FieldTripID, gorder.FieldTouristCount, gorder.FieldTransportID, gorder.FieldGuideID, gorder.FieldCost, gorder.FieldStatus, gorder.FieldPayStatus, gorder.FieldPaidSum, gorder.FieldCustomerID, gorder.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case gorder.FieldPlace, gorder.FieldComment:
			values[i] = new(sql.NullString)
		case gorder.FieldDay, gorder.FieldBegin, gorder.FieldCreated, gorder.FieldUpdated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GOrder fields.
func (_m *GOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case gorder.FieldNum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field num", values[i])
			} else if value.Valid {
				_m.Num = int(value.Int64)
			}
		case gorder.FieldTripID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trip_id", values[i])
			} else if value.Valid {
				_m.TripID = int(value.Int64)
			}
		case gorder.FieldTouristCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tourist_count", values[i])
			} else if value.Valid {
				_m.TouristCount = int(value.Int64)
			}
		case gorder.FieldDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field day", values[i])
			} else if value.Valid {
				_m.Day = value.Time
			}
		case gorder.FieldBegin:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field begin", values[i])
			} else if value.Valid {
				_m.Begin = value.Time
			}
		case gorder.FieldTransportID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field transport_id", values[i])
			} else if value.Valid {
				_m.TransportID = int(value.Int64)
			}
		case gorder.FieldGuideID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field guide_id", values[i])
			} else if value.Valid {
				_m.GuideID = int(value.Int64)
			}
		case gorder.FieldCost:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = int(value.Int64)
			}
		case gorder.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case gorder.FieldPayStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_status", values[i])
			} else if value.Valid {
				_m.PayStatus = int(value.Int64)
			}
		case gorder.FieldPaidSum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_sum", values[i])
			} else if value.Valid {
				_m.PaidSum = int(value.Int64)
			}
		case gorder.FieldCustomerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				_m.CustomerID = int(value.Int64)
			}
		case gorder.FieldPlace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field place", values[i])
			} else if value.Valid {
				_m.Place = value.String
			}
		case gorder.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = value.String
			}
		case gorder.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		case gorder.FieldUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated", values[i])
			} else if value.Valid {
				_m.Updated = value.Time
			}
		case gorder.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = int(value.Int64)
			}
		case gorder.FieldArchived:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field archived", values[i])
			} else if value.Valid {
				_m.Archived = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GOrder.
// This includes values selected through modifiers, order, etc.
func (_m *GOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GOrder.
// Note that you need to call GOrder.Unwrap() before calling this method if this GOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GOrder) Update() *GOrderUpdateOne {
	return NewGOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GOrder) Unwrap() *GOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GOrder) String() string {
	var builder strings.Builder
	builder.WriteString("GOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("num=")
	builder.WriteString(fmt.Sprintf("%v", _m.Num))
	builder.WriteString(", ")
	builder.WriteString("trip_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TripID))
	builder.WriteString(", ")
	builder.WriteString("tourist_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TouristCount))
	builder.WriteString(", ")
	builder.WriteString("day=")
	builder.WriteString(_m.Day.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("begin=")
	builder.WriteString(_m.Begin.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("transport_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TransportID))
	builder.WriteString(", ")
	builder.WriteString("guide_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GuideID))
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("pay_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayStatus))
	builder.WriteString(", ")
	builder.WriteString("paid_sum=")
	builder.WriteString(fmt.Sprintf("%v", _m.PaidSum))
	builder.WriteString(", ")
	builder.WriteString("customer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomerID))
	builder.WriteString(", ")
	builder.WriteString("place=")
	builder.WriteString(_m.Place)
	builder.WriteString(", ")
	builder.WriteString("comment=")
	builder.WriteString(_m.Comment)
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated=")
	builder.WriteString(_m.Updated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("archived=")
	builder.WriteString(fmt.Sprintf("%v", _m.Archived))
	builder.WriteByte(')')
	return builder.String()
}

// GOrders is a parsable slice of GOrder.
type GOrders []*GOrder
