// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/guide"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// GuideUpdate is the builder for updating Guide entities.
type GuideUpdate struct {
	config
	hooks    []Hook
	mutation *GuideMutation
}

// Where appends a list predicates to the GuideUpdate builder.
func (_u *GuideUpdate) Where(ps ...predicate.Guide) *GuideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFirstname sets the "firstname" field.
func (_u *GuideUpdate) SetFirstname(v string) *GuideUpdate {
	_u.mutation.SetFirstname(v)
	return _u
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (_u *GuideUpdate) SetNillableFirstname(v *string) *GuideUpdate {
	if v != nil {
		_u.SetFirstname(*v)
	}
	return _u
}

// SetLastname sets the "lastname" field.
func (_u *GuideUpdate) SetLastname(v string) *GuideUpdate {
	_u.mutation.SetLastname(v)
	return _u
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (_u *GuideUpdate) SetNillableLastname(v *string) *GuideUpdate {
	if v != nil {
		_u.SetLastname(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *GuideUpdate) SetPhone(v string) *GuideUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *GuideUpdate) SetNillablePhone(v *string) *GuideUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GuideUpdate) SetComment(v string) *GuideUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GuideUpdate) SetNillableComment(v *string) *GuideUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *GuideUpdate) SetActive(v bool) *GuideUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GuideUpdate) SetNillableActive(v *bool) *GuideUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the GuideMutation object of the builder.
func (_u *GuideUpdate) Mutation() *GuideMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GuideUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GuideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuideUpdate) check() error {
	if v, ok := _u.mutation.Firstname(); ok {
		if err := guide.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "Guide.firstname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lastname(); ok {
		if err := guide.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "Guide.lastname": %w`, err)}
		}
	}
	return nil
}

func (_u *GuideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guide.Table, guide.Columns, sqlgraph.NewFieldSpec(guide.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Firstname(); ok {
		_spec.SetField(guide.FieldFirstname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lastname(); ok {
		_spec.SetField(guide.FieldLastname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(guide.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(guide.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(guide.FieldActive, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guide.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GuideUpdateOne is the builder for updating a single Guide entity.
type GuideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GuideMutation
}

// SetFirstname sets the "firstname" field.
func (_u *GuideUpdateOne) SetFirstname(v string) *GuideUpdateOne {
	_u.mutation.SetFirstname(v)
	return _u
}

// SetNillableFirstname sets the "firstname" field if the given value is not nil.
func (_u *GuideUpdateOne) SetNillableFirstname(v *string) *GuideUpdateOne {
	if v != nil {
		_u.SetFirstname(*v)
	}
	return _u
}

// SetLastname sets the "lastname" field.
func (_u *GuideUpdateOne) SetLastname(v string) *GuideUpdateOne {
	_u.mutation.SetLastname(v)
	return _u
}

// SetNillableLastname sets the "lastname" field if the given value is not nil.
func (_u *GuideUpdateOne) SetNillableLastname(v *string) *GuideUpdateOne {
	if v != nil {
		_u.SetLastname(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *GuideUpdateOne) SetPhone(v string) *GuideUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *GuideUpdateOne) SetNillablePhone(v *string) *GuideUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *GuideUpdateOne) SetComment(v string) *GuideUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *GuideUpdateOne) SetNillableComment(v *string) *GuideUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *GuideUpdateOne) SetActive(v bool) *GuideUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *GuideUpdateOne) SetNillableActive(v *bool) *GuideUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// Mutation returns the GuideMutation object of the builder.
func (_u *GuideUpdateOne) Mutation() *GuideMutation {
	return _u.mutation
}

// Where appends a list predicates to the GuideUpdate builder.
func (_u *GuideUpdateOne) Where(ps ...predicate.Guide) *GuideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GuideUpdateOne) Select(field string, fields ...string) *GuideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Guide entity.
func (_u *GuideUpdateOne) Save(ctx context.Context) (*Guide, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuideUpdateOne) SaveX(ctx context.Context) *Guide {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GuideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuideUpdateOne) check() error {
	if v, ok := _u.mutation.Firstname(); ok {
		if err := guide.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "Guide.firstname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Lastname(); ok {
		if err := guide.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "Guide.lastname": %w`, err)}
		}
	}
	return nil
}

func (_u *GuideUpdateOne) sqlSave(ctx context.Context) (_node *Guide, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guide.Table, guide.Columns, sqlgraph.NewFieldSpec(guide.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Guide.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guide.FieldID)
		for _, f := range fields {
			if !guide.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != guide.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Firstname(); ok {
		_spec.SetField(guide.FieldFirstname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lastname(); ok {
		_spec.SetField(guide.FieldLastname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(guide.FieldPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(guide.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(guide.FieldActive, field.TypeBool, value)
	}
	_node = &Guide{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guide.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
