// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/guide"
)

// GuideCreate is the builder for creating a Guide entity.
type GuideCreate struct {
	config
	mutation *GuideMutation
	hooks    []Hook
}

// SetFirstname sets the "firstname" field.
func (_c *GuideCreate) SetFirstname(v string) *GuideCreate {
	_c.mutation.SetFirstname(v)
	return _c
}

// SetLastname sets the "lastname" field.
func (_c *GuideCreate) SetLastname(v string) *GuideCreate {
	_c.mutation.SetLastname(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *GuideCreate) SetPhone(v string) *GuideCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *GuideCreate) SetComment(v string) *GuideCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *GuideCreate) SetActive(v bool) *GuideCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *GuideCreate) SetNillableActive(v *bool) *GuideCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// Mutation returns the GuideMutation object of the builder.
func (_c *GuideCreate) Mutation() *GuideMutation {
	return _c.mutation
}

// Save creates the Guide in the database.
func (_c *GuideCreate) Save(ctx context.Context) (*Guide, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GuideCreate) SaveX(ctx context.Context) *Guide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GuideCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := guide.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GuideCreate) check() error {
	if _, ok := _c.mutation.Firstname(); !ok {
		return &ValidationError{Name: "firstname", err: errors.New(`ent: missing required field "Guide.firstname"`)}
	}
	if v, ok := _c.mutation.Firstname(); ok {
		if err := guide.FirstnameValidator(v); err != nil {
			return &ValidationError{Name: "firstname", err: fmt.Errorf(`ent: validator failed for field "Guide.firstname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Lastname(); !ok {
		return &ValidationError{Name: "lastname", err: errors.New(`ent: missing required field "Guide.lastname"`)}
	}
	if v, ok := _c.mutation.Lastname(); ok {
		if err := guide.LastnameValidator(v); err != nil {
			return &ValidationError{Name: "lastname", err: fmt.Errorf(`ent: validator failed for field "Guide.lastname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Guide.phone"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "Guide.comment"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Guide.active"`)}
	}
	return nil
}

func (_c *GuideCreate) sqlSave(ctx context.Context) (*Guide, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GuideCreate) createSpec() (*Guide, *sqlgraph.CreateSpec) {
	var (
		_node = &Guide{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(guide.Table, sqlgraph.NewFieldSpec(guide.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Firstname(); ok {
		_spec.SetField(guide.FieldFirstname, field.TypeString, value)
		_node.Firstname = value
	}
	if value, ok := _c.mutation.Lastname(); ok {
		_spec.SetField(guide.FieldLastname, field.TypeString, value)
		_node.Lastname = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(guide.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(guide.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(guide.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	return _node, _spec
}

// GuideCreateBulk is the builder for creating many Guide entities in bulk.
type GuideCreateBulk struct {
	config
	err      error
	builders []*GuideCreate
}

// Save creates the Guide entities in the database.
func (_c *GuideCreateBulk) Save(ctx context.Context) ([]*Guide, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Guide, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GuideCreateBulk) SaveX(ctx context.Context) []*Guide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
