// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/ordernumber"
)

// OrderNumber is the model entity for the OrderNumber schema.
type OrderNumber struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Num holds the value of the "num" field.
	Num          int `json:"num,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderNumber) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ordernumber.FieldID, ordernumber.FieldNum:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderNumber fields.
func (_m *OrderNumber) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ordernumber.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ordernumber.FieldNum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field num", values[i])
			} else if value.Valid {
				_m.Num = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderNumber.
// This includes values selected through modifiers, order, etc.
func (_m *OrderNumber) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OrderNumber.
// Note that you need to call OrderNumber.Unwrap() before calling this method if this OrderNumber
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderNumber) Update() *OrderNumberUpdateOne {
	return NewOrderNumberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderNumber entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderNumber) Unwrap() *OrderNumber {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderNumber is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderNumber) String() string {
	var builder strings.Builder
	builder.WriteString("OrderNumber(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("num=")
	builder.WriteString(fmt.Sprintf("%v", _m.Num))
	builder.WriteByte(')')
	return builder.String()
}

// OrderNumbers is a parsable slice of OrderNumber.
type OrderNumbers []*OrderNumber
