// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/shedule"
)

// SheduleUpdate is the builder for updating Shedule entities.
type SheduleUpdate struct {
	config
	hooks    []Hook
	mutation *SheduleMutation
}

// Where appends a list predicates to the SheduleUpdate builder.
func (_u *SheduleUpdate) Where(ps ...predicate.Shedule) *SheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *SheduleUpdate) SetResourceType(v int) *SheduleUpdate {
	_u.mutation.ResetResourceType()
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *SheduleUpdate) SetNillableResourceType(v *int) *SheduleUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// AddResourceType adds value to the "resource_type" field.
func (_u *SheduleUpdate) AddResourceType(v int) *SheduleUpdate {
	_u.mutation.AddResourceType(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *SheduleUpdate) SetResourceID(v int) *SheduleUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *SheduleUpdate) SetNillableResourceID(v *int) *SheduleUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *SheduleUpdate) AddResourceID(v int) *SheduleUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetBegin sets the "begin" field.
func (_u *SheduleUpdate) SetBegin(v time.Time) *SheduleUpdate {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *SheduleUpdate) SetNillableBegin(v *time.Time) *SheduleUpdate {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetEnd sets the "end" field.
func (_u *SheduleUpdate) SetEnd(v time.Time) *SheduleUpdate {
	_u.mutation.SetEnd(v)
	return _u
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (_u *SheduleUpdate) SetNillableEnd(v *time.Time) *SheduleUpdate {
	if v != nil {
		_u.SetEnd(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *SheduleUpdate) SetComment(v string) *SheduleUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SheduleUpdate) SetNillableComment(v *string) *SheduleUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// Mutation returns the SheduleMutation object of the builder.
func (_u *SheduleUpdate) Mutation() *SheduleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SheduleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(shedule.Table, shedule.Columns, sqlgraph.NewFieldSpec(shedule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(shedule.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceType(); ok {
		_spec.AddField(shedule.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(shedule.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(shedule.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(shedule.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.End(); ok {
		_spec.SetField(shedule.FieldEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(shedule.FieldComment, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SheduleUpdateOne is the builder for updating a single Shedule entity.
type SheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SheduleMutation
}

// SetResourceType sets the "resource_type" field.
func (_u *SheduleUpdateOne) SetResourceType(v int) *SheduleUpdateOne {
	_u.mutation.ResetResourceType()
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *SheduleUpdateOne) SetNillableResourceType(v *int) *SheduleUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// AddResourceType adds value to the "resource_type" field.
func (_u *SheduleUpdateOne) AddResourceType(v int) *SheduleUpdateOne {
	_u.mutation.AddResourceType(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *SheduleUpdateOne) SetResourceID(v int) *SheduleUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *SheduleUpdateOne) SetNillableResourceID(v *int) *SheduleUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *SheduleUpdateOne) AddResourceID(v int) *SheduleUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// SetBegin sets the "begin" field.
func (_u *SheduleUpdateOne) SetBegin(v time.Time) *SheduleUpdateOne {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *SheduleUpdateOne) SetNillableBegin(v *time.Time) *SheduleUpdateOne {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetEnd sets the "end" field.
func (_u *SheduleUpdateOne) SetEnd(v time.Time) *SheduleUpdateOne {
	_u.mutation.SetEnd(v)
	return _u
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (_u *SheduleUpdateOne) SetNillableEnd(v *time.Time) *SheduleUpdateOne {
	if v != nil {
		_u.SetEnd(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *SheduleUpdateOne) SetComment(v string) *SheduleUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SheduleUpdateOne) SetNillableComment(v *string) *SheduleUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// Mutation returns the SheduleMutation object of the builder.
func (_u *SheduleUpdateOne) Mutation() *SheduleMutation {
	return _u.mutation
}

// Where appends a list predicates to the SheduleUpdate builder.
func (_u *SheduleUpdateOne) Where(ps ...predicate.Shedule) *SheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SheduleUpdateOne) Select(field string, fields ...string) *SheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shedule entity.
func (_u *SheduleUpdateOne) Save(ctx context.Context) (*Shedule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SheduleUpdateOne) SaveX(ctx context.Context) *Shedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SheduleUpdateOne) sqlSave(ctx context.Context) (_node *Shedule, err error) {
	_spec := sqlgraph.NewUpdateSpec(shedule.Table, shedule.Columns, sqlgraph.NewFieldSpec(shedule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shedule.FieldID)
		for _, f := range fields {
			if !shedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(shedule.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceType(); ok {
		_spec.AddField(shedule.FieldResourceType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(shedule.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(shedule.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(shedule.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.End(); ok {
		_spec.SetField(shedule.FieldEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(shedule.FieldComment, field.TypeString, value)
	}
	_node = &Shedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
