// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/shedule"
)

// SheduleCreate is the builder for creating a Shedule entity.
type SheduleCreate struct {
	config
	mutation *SheduleMutation
	hooks    []Hook
}

// SetResourceType sets the "resource_type" field.
func (_c *SheduleCreate) SetResourceType(v int) *SheduleCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *SheduleCreate) SetResourceID(v int) *SheduleCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetBegin sets the "begin" field.
func (_c *SheduleCreate) SetBegin(v time.Time) *SheduleCreate {
	_c.mutation.SetBegin(v)
	return _c
}

// SetEnd sets the "end" field.
func (_c *SheduleCreate) SetEnd(v time.Time) *SheduleCreate {
	_c.mutation.SetEnd(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *SheduleCreate) SetComment(v string) *SheduleCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *SheduleCreate) SetNillableComment(v *string) *SheduleCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// Mutation returns the SheduleMutation object of the builder.
func (_c *SheduleCreate) Mutation() *SheduleMutation {
	return _c.mutation
}

// Save creates the Shedule in the database.
func (_c *SheduleCreate) Save(ctx context.Context) (*Shedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SheduleCreate) SaveX(ctx context.Context) *Shedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SheduleCreate) defaults() {
	if _, ok := _c.mutation.Comment(); !ok {
		v := shedule.DefaultComment
		_c.mutation.SetComment(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SheduleCreate) check() error {
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "Shedule.resource_type"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "Shedule.resource_id"`)}
	}
	if _, ok := _c.mutation.Begin(); !ok {
		return &ValidationError{Name: "begin", err: errors.New(`ent: missing required field "Shedule.begin"`)}
	}
	if _, ok := _c.mutation.End(); !ok {
		return &ValidationError{Name: "end", err: errors.New(`ent: missing required field "Shedule.end"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "Shedule.comment"`)}
	}
	return nil
}

func (_c *SheduleCreate) sqlSave(ctx context.Context) (*Shedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SheduleCreate) createSpec() (*Shedule, *sqlgraph.CreateSpec) {
	var (
		_node = &Shedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shedule.Table, sqlgraph.NewFieldSpec(shedule.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(shedule.FieldResourceType, field.TypeInt, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(shedule.FieldResourceID, field.TypeInt, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Begin(); ok {
		_spec.SetField(shedule.FieldBegin, field.TypeTime, value)
		_node.Begin = value
	}
	if value, ok := _c.mutation.End(); ok {
		_spec.SetField(shedule.FieldEnd, field.TypeTime, value)
		_node.End = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(shedule.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	return _node, _spec
}

// SheduleCreateBulk is the builder for creating many Shedule entities in bulk.
type SheduleCreateBulk struct {
	config
	err      error
	builders []*SheduleCreate
}

// Save creates the Shedule entities in the database.
func (_c *SheduleCreateBulk) Save(ctx context.Context) ([]*Shedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SheduleCreateBulk) SaveX(ctx context.Context) []*Shedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
