// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/transport"
)

// Transport is the model entity for the Transport schema.
type Transport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// MinCount holds the value of the "min_count" field.
	MinCount int `json:"min_count,omitempty"`
	// MaxCount holds the value of the "max_count" field.
	MaxCount int `json:"max_count,omitempty"`
	// Active holds the value of the "active" field.
	Active       bool `json:"active,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transport.FieldActive:
			values[i] = new(sql.NullBool)
		case transport.FieldID, transport.FieldMinCount, transport.FieldMaxCount:
			values[i] = new(sql.NullInt64)
		case transport.FieldName, transport.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transport fields.
func (_m *Transport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case transport.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case transport.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case transport.FieldMinCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_count", values[i])
			} else if value.Valid {
				_m.MinCount = int(value.Int64)
			}
		case transport.FieldMaxCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_count", values[i])
			} else if value.Valid {
				_m.MaxCount = int(value.Int64)
			}
		case transport.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transport.
// This includes values selected through modifiers, order, etc.
func (_m *Transport) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Transport.
// Note that you need to call Transport.Unwrap() before calling this method if this Transport
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Transport) Update() *TransportUpdateOne {
	return NewTransportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Transport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Transport) Unwrap() *Transport {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transport is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Transport) String() string {
	var builder strings.Builder
	builder.WriteString("Transport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("min_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinCount))
	builder.WriteString(", ")
	builder.WriteString("max_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxCount))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteByte(')')
	return builder.String()
}

// Transports is a parsable slice of Transport.
type Transports []*Transport
