// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/trip"
)

// TripCreate is the builder for creating a Trip entity.
type TripCreate struct {
	config
	mutation *TripMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TripCreate) SetName(v string) *TripCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TripCreate) SetDescription(v string) *TripCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *TripCreate) SetComment(v string) *TripCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetDuration sets the "duration" field.
func (_c *TripCreate) SetDuration(v time.Time) *TripCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *TripCreate) SetActive(v bool) *TripCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *TripCreate) SetNillableActive(v *bool) *TripCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetBegin sets the "begin" field.
func (_c *TripCreate) SetBegin(v time.Time) *TripCreate {
	_c.mutation.SetBegin(v)
	return _c
}

// SetEnd sets the "end" field.
func (_c *TripCreate) SetEnd(v time.Time) *TripCreate {
	_c.mutation.SetEnd(v)
	return _c
}

// SetPhoto sets the "photo" field.
func (_c *TripCreate) SetPhoto(v string) *TripCreate {
	_c.mutation.SetPhoto(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TripCreate) SetType(v int) *TripCreate {
	_c.mutation.SetType(v)
	return _c
}

// Mutation returns the TripMutation object of the builder.
func (_c *TripCreate) Mutation() *TripMutation {
	return _c.mutation
}

// Save creates the Trip in the database.
func (_c *TripCreate) Save(ctx context.Context) (*Trip, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TripCreate) SaveX(ctx context.Context) *Trip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TripCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TripCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TripCreate) defaults() {
	if _, ok := _c.mutation.Active(); !ok {
		v := trip.DefaultActive
		_c.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TripCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Trip.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := trip.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Trip.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Trip.description"`)}
	}
	if _, ok := _c.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "Trip.comment"`)}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "Trip.duration"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Trip.active"`)}
	}
	if _, ok := _c.mutation.Begin(); !ok {
		return &ValidationError{Name: "begin", err: errors.New(`ent: missing required field "Trip.begin"`)}
	}
	if _, ok := _c.mutation.End(); !ok {
		return &ValidationError{Name: "end", err: errors.New(`ent: missing required field "Trip.end"`)}
	}
	if _, ok := _c.mutation.Photo(); !ok {
		return &ValidationError{Name: "photo", err: errors.New(`ent: missing required field "Trip.photo"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Trip.type"`)}
	}
	return nil
}

func (_c *TripCreate) sqlSave(ctx context.Context) (*Trip, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TripCreate) createSpec() (*Trip, *sqlgraph.CreateSpec) {
	var (
		_node = &Trip{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trip.Table, sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(trip.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(trip.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(trip.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(trip.FieldDuration, field.TypeTime, value)
		_node.Duration = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(trip.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.Begin(); ok {
		_spec.SetField(trip.FieldBegin, field.TypeTime, value)
		_node.Begin = value
	}
	if value, ok := _c.mutation.End(); ok {
		_spec.SetField(trip.FieldEnd, field.TypeTime, value)
		_node.End = value
	}
	if value, ok := _c.mutation.Photo(); ok {
		_spec.SetField(trip.FieldPhoto, field.TypeString, value)
		_node.Photo = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(trip.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	return _node, _spec
}

// TripCreateBulk is the builder for creating many Trip entities in bulk.
type TripCreateBulk struct {
	config
	err      error
	builders []*TripCreate
}

// Save creates the Trip entities in the database.
func (_c *TripCreateBulk) Save(ctx context.Context) ([]*Trip, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Trip, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TripMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TripCreateBulk) SaveX(ctx context.Context) []*Trip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TripCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TripCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
