// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/trip"
)

// TripUpdate is the builder for updating Trip entities.
type TripUpdate struct {
	config
	hooks    []Hook
	mutation *TripMutation
}

// Where appends a list predicates to the TripUpdate builder.
func (_u *TripUpdate) Where(ps ...predicate.Trip) *TripUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TripUpdate) SetName(v string) *TripUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TripUpdate) SetNillableName(v *string) *TripUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TripUpdate) SetDescription(v string) *TripUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TripUpdate) SetNillableDescription(v *string) *TripUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *TripUpdate) SetComment(v string) *TripUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *TripUpdate) SetNillableComment(v *string) *TripUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetDuration sets the "duration" field.
func (_u *TripUpdate) SetDuration(v time.Time) *TripUpdate {
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *TripUpdate) SetNillableDuration(v *time.Time) *TripUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *TripUpdate) SetActive(v bool) *TripUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *TripUpdate) SetNillableActive(v *bool) *TripUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetBegin sets the "begin" field.
func (_u *TripUpdate) SetBegin(v time.Time) *TripUpdate {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *TripUpdate) SetNillableBegin(v *time.Time) *TripUpdate {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetEnd sets the "end" field.
func (_u *TripUpdate) SetEnd(v time.Time) *TripUpdate {
	_u.mutation.SetEnd(v)
	return _u
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (_u *TripUpdate) SetNillableEnd(v *time.Time) *TripUpdate {
	if v != nil {
		_u.SetEnd(*v)
	}
	return _u
}

// SetPhoto sets the "photo" field.
func (_u *TripUpdate) SetPhoto(v string) *TripUpdate {
	_u.mutation.SetPhoto(v)
	return _u
}

// SetNillablePhoto sets the "photo" field if the given value is not nil.
func (_u *TripUpdate) SetNillablePhoto(v *string) *TripUpdate {
	if v != nil {
		_u.SetPhoto(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TripUpdate) SetType(v int) *TripUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TripUpdate) SetNillableType(v *int) *TripUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *TripUpdate) AddType(v int) *TripUpdate {
	_u.mutation.AddType(v)
	return _u
}

// Mutation returns the TripMutation object of the builder.
func (_u *TripUpdate) Mutation() *TripMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TripUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TripUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TripUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TripUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TripUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := trip.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Trip.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TripUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trip.Table, trip.Columns, sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(trip.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(trip.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(trip.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(trip.FieldDuration, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(trip.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(trip.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.End(); ok {
		_spec.SetField(trip.FieldEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Photo(); ok {
		_spec.SetField(trip.FieldPhoto, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(trip.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(trip.FieldType, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TripUpdateOne is the builder for updating a single Trip entity.
type TripUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TripMutation
}

// SetName sets the "name" field.
func (_u *TripUpdateOne) SetName(v string) *TripUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableName(v *string) *TripUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TripUpdateOne) SetDescription(v string) *TripUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableDescription(v *string) *TripUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *TripUpdateOne) SetComment(v string) *TripUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableComment(v *string) *TripUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// SetDuration sets the "duration" field.
func (_u *TripUpdateOne) SetDuration(v time.Time) *TripUpdateOne {
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableDuration(v *time.Time) *TripUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *TripUpdateOne) SetActive(v bool) *TripUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableActive(v *bool) *TripUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetBegin sets the "begin" field.
func (_u *TripUpdateOne) SetBegin(v time.Time) *TripUpdateOne {
	_u.mutation.SetBegin(v)
	return _u
}

// SetNillableBegin sets the "begin" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableBegin(v *time.Time) *TripUpdateOne {
	if v != nil {
		_u.SetBegin(*v)
	}
	return _u
}

// SetEnd sets the "end" field.
func (_u *TripUpdateOne) SetEnd(v time.Time) *TripUpdateOne {
	_u.mutation.SetEnd(v)
	return _u
}

// SetNillableEnd sets the "end" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableEnd(v *time.Time) *TripUpdateOne {
	if v != nil {
		_u.SetEnd(*v)
	}
	return _u
}

// SetPhoto sets the "photo" field.
func (_u *TripUpdateOne) SetPhoto(v string) *TripUpdateOne {
	_u.mutation.SetPhoto(v)
	return _u
}

// SetNillablePhoto sets the "photo" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillablePhoto(v *string) *TripUpdateOne {
	if v != nil {
		_u.SetPhoto(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *TripUpdateOne) SetType(v int) *TripUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TripUpdateOne) SetNillableType(v *int) *TripUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *TripUpdateOne) AddType(v int) *TripUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// Mutation returns the TripMutation object of the builder.
func (_u *TripUpdateOne) Mutation() *TripMutation {
	return _u.mutation
}

// Where appends a list predicates to the TripUpdate builder.
func (_u *TripUpdateOne) Where(ps ...predicate.Trip) *TripUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TripUpdateOne) Select(field string, fields ...string) *TripUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Trip entity.
func (_u *TripUpdateOne) Save(ctx context.Context) (*Trip, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TripUpdateOne) SaveX(ctx context.Context) *Trip {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TripUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TripUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TripUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := trip.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Trip.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TripUpdateOne) sqlSave(ctx context.Context) (_node *Trip, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trip.Table, trip.Columns, sqlgraph.NewFieldSpec(trip.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Trip.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trip.FieldID)
		for _, f := range fields {
			if !trip.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(trip.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(trip.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(trip.FieldComment, field.TypeString, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(trip.FieldDuration, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(trip.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Begin(); ok {
		_spec.SetField(trip.FieldBegin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.End(); ok {
		_spec.SetField(trip.FieldEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Photo(); ok {
		_spec.SetField(trip.FieldPhoto, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(trip.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(trip.FieldType, field.TypeInt, value)
	}
	_node = &Trip{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
