// Code generated by ent, DO NOT EDIT.

package shedule

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the shedule type in the database.
	Label = "shedule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldBegin holds the string denoting the begin field in the database.
	FieldBegin = "begin"
	// FieldEnd holds the string denoting the end field in the database.
	FieldEnd = "end"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// Table holds the table name of the shedule in the database.
	Table = "shedules"
)

// Columns holds all SQL columns for shedule fields.
var Columns = []string{
	FieldID,
	FieldResourceType,
	FieldResourceID,
	FieldBegin,
	FieldEnd,
	FieldComment,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultComment holds the default value on creation for the "comment" field.
	DefaultComment string
)

// OrderOption defines the ordering options for the Shedule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByBegin orders the results by the begin field.
func ByBegin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBegin, opts...).ToFunc()
}

// ByEnd orders the results by the end field.
func ByEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnd, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}
