// Code generated by ent, DO NOT EDIT.

package gcost

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gcost type in the database.
	Label = "gcost"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldTripID holds the string denoting the trip_id field in the database.
	FieldTripID = "trip_id"
	// FieldTransportID holds the string denoting the transport_id field in the database.
	FieldTransportID = "transport_id"
	// Table holds the table name of the gcost in the database.
	Table = "gcosts"
)

// Columns holds all SQL columns for gcost fields.
var Columns = []string{
	FieldID,
	FieldCost,
	FieldTripID,
	FieldTransportID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost int
	// DefaultTripID holds the default value on creation for the "trip_id" field.
	DefaultTripID int
	// DefaultTransportID holds the default value on creation for the "transport_id" field.
	DefaultTransportID int
)

// OrderOption defines the ordering options for the GCost queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByTripID orders the results by the trip_id field.
func ByTripID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTripID, opts...).ToFunc()
}

// ByTransportID orders the results by the transport_id field.
func ByTransportID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransportID, opts...).ToFunc()
}
