// Code generated by ent, DO NOT EDIT.

package gcost

import (
	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GCost {
	return predicate.GCost(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GCost {
	return predicate.GCost(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GCost {
	return predicate.GCost(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GCost {
	return predicate.GCost(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GCost {
	return predicate.GCost(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GCost {
	return predicate.GCost(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GCost {
	return predicate.GCost(sql.FieldLTE(FieldID, id))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldCost, v))
}

// TripID applies equality check predicate on the "trip_id" field. It's identical to TripIDEQ.
func TripID(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldTripID, v))
}

// TransportID applies equality check predicate on the "transport_id" field. It's identical to TransportIDEQ.
func TransportID(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldTransportID, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLTE(FieldCost, v))
}

// TripIDEQ applies the EQ predicate on the "trip_id" field.
func TripIDEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldTripID, v))
}

// TripIDNEQ applies the NEQ predicate on the "trip_id" field.
func TripIDNEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldNEQ(FieldTripID, v))
}

// TripIDIn applies the In predicate on the "trip_id" field.
func TripIDIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldIn(FieldTripID, vs...))
}

// TripIDNotIn applies the NotIn predicate on the "trip_id" field.
func TripIDNotIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldNotIn(FieldTripID, vs...))
}

// TripIDGT applies the GT predicate on the "trip_id" field.
func TripIDGT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGT(FieldTripID, v))
}

// TripIDGTE applies the GTE predicate on the "trip_id" field.
func TripIDGTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGTE(FieldTripID, v))
}

// TripIDLT applies the LT predicate on the "trip_id" field.
func TripIDLT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLT(FieldTripID, v))
}

// TripIDLTE applies the LTE predicate on the "trip_id" field.
func TripIDLTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLTE(FieldTripID, v))
}

// TransportIDEQ applies the EQ predicate on the "transport_id" field.
func TransportIDEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldEQ(FieldTransportID, v))
}

// TransportIDNEQ applies the NEQ predicate on the "transport_id" field.
func TransportIDNEQ(v int) predicate.GCost {
	return predicate.GCost(sql.FieldNEQ(FieldTransportID, v))
}

// TransportIDIn applies the In predicate on the "transport_id" field.
func TransportIDIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldIn(FieldTransportID, vs...))
}

// TransportIDNotIn applies the NotIn predicate on the "transport_id" field.
func TransportIDNotIn(vs ...int) predicate.GCost {
	return predicate.GCost(sql.FieldNotIn(FieldTransportID, vs...))
}

// TransportIDGT applies the GT predicate on the "transport_id" field.
func TransportIDGT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGT(FieldTransportID, v))
}

// TransportIDGTE applies the GTE predicate on the "transport_id" field.
func TransportIDGTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldGTE(FieldTransportID, v))
}

// TransportIDLT applies the LT predicate on the "transport_id" field.
func TransportIDLT(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLT(FieldTransportID, v))
}

// TransportIDLTE applies the LTE predicate on the "transport_id" field.
func TransportIDLTE(v int) predicate.GCost {
	return predicate.GCost(sql.FieldLTE(FieldTransportID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GCost) predicate.GCost {
	return predicate.GCost(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GCost) predicate.GCost {
	return predicate.GCost(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GCost) predicate.GCost {
	return predicate.GCost(sql.NotPredicates(p))
}
