// Code generated by ent, DO NOT EDIT.

package gorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/mikestefanello/pagoda/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldID, id))
}

// Num applies equality check predicate on the "num" field. It's identical to NumEQ.
func Num(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldNum, v))
}

// TripID applies equality check predicate on the "trip_id" field. It's identical to TripIDEQ.
func TripID(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTripID, v))
}

// TouristCount applies equality check predicate on the "tourist_count" field. It's identical to TouristCountEQ.
func TouristCount(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTouristCount, v))
}

// Day applies equality check predicate on the "day" field. It's identical to DayEQ.
func Day(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldDay, v))
}

// Begin applies equality check predicate on the "begin" field. It's identical to BeginEQ.
func Begin(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldBegin, v))
}

// TransportID applies equality check predicate on the "transport_id" field. It's identical to TransportIDEQ.
func TransportID(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTransportID, v))
}

// GuideID applies equality check predicate on the "guide_id" field. It's identical to GuideIDEQ.
func GuideID(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldGuideID, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCost, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldStatus, v))
}

// PayStatus applies equality check predicate on the "pay_status" field. It's identical to PayStatusEQ.
func PayStatus(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPayStatus, v))
}

// PaidSum applies equality check predicate on the "paid_sum" field. It's identical to PaidSumEQ.
func PaidSum(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPaidSum, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCustomerID, v))
}

// Place applies equality check predicate on the "place" field. It's identical to PlaceEQ.
func Place(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPlace, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldComment, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCreated, v))
}

// Updated applies equality check predicate on the "updated" field. It's identical to UpdatedEQ.
func Updated(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldUpdated, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// Archived applies equality check predicate on the "archived" field. It's identical to ArchivedEQ.
func Archived(v bool) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldArchived, v))
}

// NumEQ applies the EQ predicate on the "num" field.
func NumEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldNum, v))
}

// NumNEQ applies the NEQ predicate on the "num" field.
func NumNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldNum, v))
}

// NumIn applies the In predicate on the "num" field.
func NumIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldNum, vs...))
}

// NumNotIn applies the NotIn predicate on the "num" field.
func NumNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldNum, vs...))
}

// NumGT applies the GT predicate on the "num" field.
func NumGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldNum, v))
}

// NumGTE applies the GTE predicate on the "num" field.
func NumGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldNum, v))
}

// NumLT applies the LT predicate on the "num" field.
func NumLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldNum, v))
}

// NumLTE applies the LTE predicate on the "num" field.
func NumLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldNum, v))
}

// TripIDEQ applies the EQ predicate on the "trip_id" field.
func TripIDEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTripID, v))
}

// TripIDNEQ applies the NEQ predicate on the "trip_id" field.
func TripIDNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldTripID, v))
}

// TripIDIn applies the In predicate on the "trip_id" field.
func TripIDIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldTripID, vs...))
}

// TripIDNotIn applies the NotIn predicate on the "trip_id" field.
func TripIDNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldTripID, vs...))
}

// TripIDGT applies the GT predicate on the "trip_id" field.
func TripIDGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldTripID, v))
}

// TripIDGTE applies the GTE predicate on the "trip_id" field.
func TripIDGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldTripID, v))
}

// TripIDLT applies the LT predicate on the "trip_id" field.
func TripIDLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldTripID, v))
}

// TripIDLTE applies the LTE predicate on the "trip_id" field.
func TripIDLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldTripID, v))
}

// TouristCountEQ applies the EQ predicate on the "tourist_count" field.
func TouristCountEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTouristCount, v))
}

// TouristCountNEQ applies the NEQ predicate on the "tourist_count" field.
func TouristCountNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldTouristCount, v))
}

// TouristCountIn applies the In predicate on the "tourist_count" field.
func TouristCountIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldTouristCount, vs...))
}

// TouristCountNotIn applies the NotIn predicate on the "tourist_count" field.
func TouristCountNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldTouristCount, vs...))
}

// TouristCountGT applies the GT predicate on the "tourist_count" field.
func TouristCountGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldTouristCount, v))
}

// TouristCountGTE applies the GTE predicate on the "tourist_count" field.
func TouristCountGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldTouristCount, v))
}

// TouristCountLT applies the LT predicate on the "tourist_count" field.
func TouristCountLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldTouristCount, v))
}

// TouristCountLTE applies the LTE predicate on the "tourist_count" field.
func TouristCountLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldTouristCount, v))
}

// DayEQ applies the EQ predicate on the "day" field.
func DayEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldDay, v))
}

// DayNEQ applies the NEQ predicate on the "day" field.
func DayNEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldDay, v))
}

// DayIn applies the In predicate on the "day" field.
func DayIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldDay, vs...))
}

// DayNotIn applies the NotIn predicate on the "day" field.
func DayNotIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldDay, vs...))
}

// DayGT applies the GT predicate on the "day" field.
func DayGT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldDay, v))
}

// DayGTE applies the GTE predicate on the "day" field.
func DayGTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldDay, v))
}

// DayLT applies the LT predicate on the "day" field.
func DayLT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldDay, v))
}

// DayLTE applies the LTE predicate on the "day" field.
func DayLTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldDay, v))
}

// BeginEQ applies the EQ predicate on the "begin" field.
func BeginEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldBegin, v))
}

// BeginNEQ applies the NEQ predicate on the "begin" field.
func BeginNEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldBegin, v))
}

// BeginIn applies the In predicate on the "begin" field.
func BeginIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldBegin, vs...))
}

// BeginNotIn applies the NotIn predicate on the "begin" field.
func BeginNotIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldBegin, vs...))
}

// BeginGT applies the GT predicate on the "begin" field.
func BeginGT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldBegin, v))
}

// BeginGTE applies the GTE predicate on the "begin" field.
func BeginGTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldBegin, v))
}

// BeginLT applies the LT predicate on the "begin" field.
func BeginLT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldBegin, v))
}

// BeginLTE applies the LTE predicate on the "begin" field.
func BeginLTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldBegin, v))
}

// TransportIDEQ applies the EQ predicate on the "transport_id" field.
func TransportIDEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldTransportID, v))
}

// TransportIDNEQ applies the NEQ predicate on the "transport_id" field.
func TransportIDNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldTransportID, v))
}

// TransportIDIn applies the In predicate on the "transport_id" field.
func TransportIDIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldTransportID, vs...))
}

// TransportIDNotIn applies the NotIn predicate on the "transport_id" field.
func TransportIDNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldTransportID, vs...))
}

// TransportIDGT applies the GT predicate on the "transport_id" field.
func TransportIDGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldTransportID, v))
}

// TransportIDGTE applies the GTE predicate on the "transport_id" field.
func TransportIDGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldTransportID, v))
}

// TransportIDLT applies the LT predicate on the "transport_id" field.
func TransportIDLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldTransportID, v))
}

// TransportIDLTE applies the LTE predicate on the "transport_id" field.
func TransportIDLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldTransportID, v))
}

// GuideIDEQ applies the EQ predicate on the "guide_id" field.
func GuideIDEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldGuideID, v))
}

// GuideIDNEQ applies the NEQ predicate on the "guide_id" field.
func GuideIDNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldGuideID, v))
}

// GuideIDIn applies the In predicate on the "guide_id" field.
func GuideIDIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldGuideID, vs...))
}

// GuideIDNotIn applies the NotIn predicate on the "guide_id" field.
func GuideIDNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldGuideID, vs...))
}

// GuideIDGT applies the GT predicate on the "guide_id" field.
func GuideIDGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldGuideID, v))
}

// GuideIDGTE applies the GTE predicate on the "guide_id" field.
func GuideIDGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldGuideID, v))
}

// GuideIDLT applies the LT predicate on the "guide_id" field.
func GuideIDLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldGuideID, v))
}

// GuideIDLTE applies the LTE predicate on the "guide_id" field.
func GuideIDLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldGuideID, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldCost, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldStatus, v))
}

// PayStatusEQ applies the EQ predicate on the "pay_status" field.
func PayStatusEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPayStatus, v))
}

// PayStatusNEQ applies the NEQ predicate on the "pay_status" field.
func PayStatusNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldPayStatus, v))
}

// PayStatusIn applies the In predicate on the "pay_status" field.
func PayStatusIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldPayStatus, vs...))
}

// PayStatusNotIn applies the NotIn predicate on the "pay_status" field.
func PayStatusNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldPayStatus, vs...))
}

// PayStatusGT applies the GT predicate on the "pay_status" field.
func PayStatusGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldPayStatus, v))
}

// PayStatusGTE applies the GTE predicate on the "pay_status" field.
func PayStatusGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldPayStatus, v))
}

// PayStatusLT applies the LT predicate on the "pay_status" field.
func PayStatusLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldPayStatus, v))
}

// PayStatusLTE applies the LTE predicate on the "pay_status" field.
func PayStatusLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldPayStatus, v))
}

// PaidSumEQ applies the EQ predicate on the "paid_sum" field.
func PaidSumEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPaidSum, v))
}

// PaidSumNEQ applies the NEQ predicate on the "paid_sum" field.
func PaidSumNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldPaidSum, v))
}

// PaidSumIn applies the In predicate on the "paid_sum" field.
func PaidSumIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldPaidSum, vs...))
}

// PaidSumNotIn applies the NotIn predicate on the "paid_sum" field.
func PaidSumNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldPaidSum, vs...))
}

// PaidSumGT applies the GT predicate on the "paid_sum" field.
func PaidSumGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldPaidSum, v))
}

// PaidSumGTE applies the GTE predicate on the "paid_sum" field.
func PaidSumGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldPaidSum, v))
}

// PaidSumLT applies the LT predicate on the "paid_sum" field.
func PaidSumLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldPaidSum, v))
}

// PaidSumLTE applies the LTE predicate on the "paid_sum" field.
func PaidSumLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldPaidSum, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldCustomerID, v))
}

// PlaceEQ applies the EQ predicate on the "place" field.
func PlaceEQ(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldPlace, v))
}

// PlaceNEQ applies the NEQ predicate on the "place" field.
func PlaceNEQ(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldPlace, v))
}

// PlaceIn applies the In predicate on the "place" field.
func PlaceIn(vs ...string) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldPlace, vs...))
}

// PlaceNotIn applies the NotIn predicate on the "place" field.
func PlaceNotIn(vs ...string) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldPlace, vs...))
}

// PlaceGT applies the GT predicate on the "place" field.
func PlaceGT(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldPlace, v))
}

// PlaceGTE applies the GTE predicate on the "place" field.
func PlaceGTE(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldPlace, v))
}

// PlaceLT applies the LT predicate on the "place" field.
func PlaceLT(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldPlace, v))
}

// PlaceLTE applies the LTE predicate on the "place" field.
func PlaceLTE(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldPlace, v))
}

// PlaceContains applies the Contains predicate on the "place" field.
func PlaceContains(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldContains(FieldPlace, v))
}

// PlaceHasPrefix applies the HasPrefix predicate on the "place" field.
func PlaceHasPrefix(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldHasPrefix(FieldPlace, v))
}

// PlaceHasSuffix applies the HasSuffix predicate on the "place" field.
func PlaceHasSuffix(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldHasSuffix(FieldPlace, v))
}

// PlaceEqualFold applies the EqualFold predicate on the "place" field.
func PlaceEqualFold(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEqualFold(FieldPlace, v))
}

// PlaceContainsFold applies the ContainsFold predicate on the "place" field.
func PlaceContainsFold(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldContainsFold(FieldPlace, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldHasSuffix(FieldComment, v))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.GOrder {
	return predicate.GOrder(sql.FieldContainsFold(FieldComment, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldCreated, v))
}

// UpdatedEQ applies the EQ predicate on the "updated" field.
func UpdatedEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldUpdated, v))
}

// UpdatedNEQ applies the NEQ predicate on the "updated" field.
func UpdatedNEQ(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldUpdated, v))
}

// UpdatedIn applies the In predicate on the "updated" field.
func UpdatedIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldUpdated, vs...))
}

// UpdatedNotIn applies the NotIn predicate on the "updated" field.
func UpdatedNotIn(vs ...time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldUpdated, vs...))
}

// UpdatedGT applies the GT predicate on the "updated" field.
func UpdatedGT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldUpdated, v))
}

// UpdatedGTE applies the GTE predicate on the "updated" field.
func UpdatedGTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldUpdated, v))
}

// UpdatedLT applies the LT predicate on the "updated" field.
func UpdatedLT(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldUpdated, v))
}

// UpdatedLTE applies the LTE predicate on the "updated" field.
func UpdatedLTE(v time.Time) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldUpdated, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.GOrder {
	return predicate.GOrder(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.GOrder {
	return predicate.GOrder(sql.FieldLTE(FieldCreatedBy, v))
}

// ArchivedEQ applies the EQ predicate on the "archived" field.
func ArchivedEQ(v bool) predicate.GOrder {
	return predicate.GOrder(sql.FieldEQ(FieldArchived, v))
}

// ArchivedNEQ applies the NEQ predicate on the "archived" field.
func ArchivedNEQ(v bool) predicate.GOrder {
	return predicate.GOrder(sql.FieldNEQ(FieldArchived, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GOrder) predicate.GOrder {
	return predicate.GOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GOrder) predicate.GOrder {
	return predicate.GOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GOrder) predicate.GOrder {
	return predicate.GOrder(sql.NotPredicates(p))
}
