// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cost is the predicate function for cost builders.
type Cost func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// GLog is the predicate function for glog builders.
type GLog func(*sql.Selector)

// GOrder is the predicate function for gorder builders.
type GOrder func(*sql.Selector)

// Guide is the predicate function for guide builders.
type Guide func(*sql.Selector)

// OrderNumber is the predicate function for ordernumber builders.
type OrderNumber func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// Shedule is the predicate function for shedule builders.
type Shedule func(*sql.Selector)

// Transport is the predicate function for transport builders.
type Transport func(*sql.Selector)

// Trip is the predicate function for trip builders.
type Trip func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
